---
title: Useful RStudio Keyboard Shortcuts
author: Andrew Brown
date: "`r Sys.Date()`"
output:  html_document
---

Here are some of the most useful RStudio keyboard shortcuts (the ones I use hundreds of times a week). 

Mastering these shortcuts, and being aware of the many less-common ones, will make your work in RStudio more efficient.

***

#### RUNNING CODE

 * __Ctrl + Enter__ - _Run current line or selection in Editor pane_

 * __Ctrl + Shift + Enter__ - _Source the current document (or selected chunk when in .Rmd)_

***

#### MANIPULATING THE R ENVIRONMENT

 * __Ctrl + L__ - _Clear console or terminal_

 * __Ctrl + Shift + H__ - _Change working directory..._

 * __Ctrl + Shift + F10__ - _Restart R session_


 * __Ctrl + 1__ - _Move focus to Source Editor_

 * __Ctrl + 2__ - _Move focus to Console_

 * __Ctrl + 3__ - _Move focus to Help_
 
*** 

#### EDITING CODE

 * __Home__ - _Move cursor to beginning of line_

 * __End__ - _Move cursor to end of line_
 
***

#### AUTOMATIC CODE COMPLETION

 * __Tab__ / __Ctrl + Space__ - _Attempt completion_

 * __Enter__, __Tab__, or __Right Arrow__ - _Accept selected candidate_

 * __Esc__ - _Dismiss completion popup_

***

And there are _many, many, many_ more! 

See:

 * __Alt + Shift + K__ - _Show Keyboard Shortcut Reference_

 * [RStudio Support - Keyboard Shortcuts](https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcut)