# Stats for Soil Survey Part 1 

## Introduction to R and RStudio

**Keywords:** R, packages, working directory, RStudio Projects, R Scripts, R Markdown, R Workspace, R History, R Graphics, Filter, Subset, Transform, Sort, Pipe, Merge, Join, Aggregate, Reshape, Export

### Why is this training needed?                 
### Why is course organized this way?            
### Why Should I Learn R?                        
### What can R do?                               
### Packages                                     
### Installing Packages                          
### Loading Packages                             
### Basic Tips for Scripting                     
### Setting the Working Directory                
### RStudio Projects (.Rproj files)              
### More RStudio Project Features                
#### R script (.R)                               
#### Microsoft Word Files                        
#### R Markdown (.Rmd)                           
#### Workspace (.Rdata)                          
#### R history (.Rhistory)                       
#### R Graphics                                  
#### Text files                                  
#### Excel files                                 
#### NASIS (Web) Reports                         
### Viewing and Removing Data                    
### Filtering or Subsetting Data                 
### Transforming Data                            
### Sorting Data                                 
### Piping Data                                  
### Merging/Joining or Combining Data            
### Aggregating or Grouping Data                 
### Reshaping Data                               
### Exporting Data                               

## The Data We Use

**Keywords:** soilDB R package, aqp R package, pedon data, SoilProfileCollection, promoting to SoilProfileCollection, extracting site data, extracting horizon data, data.frame-like methods, column access, row access, fetchNASIS, arguments to fetchNASIS, gopheridge, profile sketches, plotSPC, fetchNASIS data checks, table, dput, missing data, logical operators, logical expressions, regular expressions, pattern matching, REGEX Quick Start, REGEX Resources, filtering SoilProfileCollections, dates and times in R, extended NASIS data, get_extended_data_from_NASIS_db, boolean diagnostic features, custom NASIS queries, soilReports R package, shiny pedon summary dashboard report, mapunit comparison report, lab summary by taxon name report.

### Package References                                                   
### soilDB functions for tabular data                                    
### Importance of Pedon Data                                             
### Some Issues With Pedon Data                                          
### Meeting the Challenges                                               
### `SoilProfileCollection` methods                                      
#### Promoting a `data.frame` to `SoilProfileCollection`                 
### Extending the `SoilProfileCollection` Spatial Model                  
#### Extracting Site and Horizon Data                                    
#### Methods like `data.frame`                                           
##### Column Access by Name: `$` and `[[`                                
##### Row Access: `[`                                                    
##### Optional: `tibble` and `data.table` `SoilProfileCollection` objects
### Why bother with a `SoilProfileCollection`?                           
### Open Database Connectivity (ODBC) Connection to NASIS                
### `fetchNASIS()`                                                       
#### fetchNASIS arguments                                                
### The `gopheridge` Dataset                                             
#### Make profile sketches                                               
#### Pedon Data Checks                                                   
#### Find Pedons with Errors                                             
### Further Reading / Reference                                          
### Summaries                                                            
#### `table()`                                                           
#### `dput()`                                                            
#### The `dplyr` package and \tidy\ data principles                    
##### `dplyr` and `aqp`                                                  
### Missing Values                                                       
### Logical Operators                                                    
### Pattern Matching                                                     
#### REGEX Quick Start                                                   
#### Resources for Regular Expressions                                   
### Filtering                                                            
#### Filtering with `aqp::subset`                                        
### Dates and Times                                                      
#### Packages for Time-series Data                                       
### Inspecting Results                                                   
#### Load Example Data                                                   
#### Logic Checks for the `SoilProfileCollection`                        
### Elements of `get_extended_data_from_NASIS()`                         
### Load Example Data                                                    
### Visualizing Common Landforms                                         
###  Diagnostic Features                                                 
#### Boolean Diagnostic Features in `fetchNASIS`                         
#### Thickness from Diagnostic Features Table                            
#### Diagnostic Feature Diagrams                                         
### Comparing Horizon Data with Diagnostic \Intervals\                 
#### Follow along with your own data                                     
### `RODBC` package                                                      
### `DBI`                                                                
### Extending `soilReports`                                              
### Exercise: Run Shiny Pedon Summary                                    
### Exercise: Run Mapunit Comparison                                     
### Exercise: Run Lab Summary By Taxon Name Soil Report                  


## Exploratory data analysis
 
**Keywords:** measures of central tendency, measures of dispersion, correlation, distribution, bar plot, histogram, density curve, box plots, Q-Q plot, quantile comparison plots, the Normal distribution, scatter plots, line plots, graph symbology, color, groups, facets (box plot), facets(depth plot), transformations, pH data transformation, circular data, texture and compositional data, shiny apps, web apps, troubleshooting web apps, embedding shiny apps, example NASIS reports

### Measures of Central Tendency                      
### Measures of Dispersion                            
### Correlation                                       
### Distributions                                     
### Bar Plot                                          
### Histogram                                         
### Density Curve                                     
### Box plots                                         
### Quantile comparison plots (QQplot)                
### The 'Normal' distribution                         
### Scatterplots and Line Plots                       
### 3rd Dimension - Color, Shape, Size, Layers, etc...
#### Color and Groups                                 
#### Facets - box plots                               
#### Facets - depth plots                             
### pH                                                
### Circular data                                     
### Texture                                           
### Online                                            
### Locally                                           
### Web App Demonstration                             
### Troubleshooting Errors                            
### Shiny App Embedding                               
#### Shiny App Code                                   
### Questions                                         
### Examples                                          
#### NASIS Reports                                    
#### Water Table                                      
#### Organic Matter                                   
#### Project Report                                   
#### Project Extent                                   
#### Long Range Plan                                  
#### Interpretations                                  
### Work on your Own                                  
#### Project Report                                   
#### Project Extent                                   
#### Long Range Plan      

## Spatial Data
**Keywords:** geographic data, spatial data sources, making maps with R, make interactive plot of NASIS points, save NASIS points to shapefile, save NASIS points to Google Earth KML, the sf R package, the sp R package, converting between sf and sp, importing/exporting vector data, interactive plots with mapview and leaflet R packages, soil series extents with SoilWeb, the raster R package, importing/exporting raster data, raster object properties, raster compression, converting vector to raster, coordinate reference systems, spatial overlay operations (vector), spatial overlay operations (raster), extracting raster data from points, extracting raster data from polygons, faster raster extraction with the exactextractr R package

### Plotting Geographic Data                                                                            
#### Interactive `mapview`  
#### Create a subset         
#### Saving to Shapefile         
#### Export for Google Earth (_.kml_)      
### The `sf` package     
#### `sf` vignettes    
### The `sp` Package  
### Converting `sp` and `sf` 
### Importing / Exporting Vector Data           
#### `sf`        
#### `sp` / `rgdal`        
### Interactive mapping with `mapview` and `leaflet`      
#### EXERCISE 2: Map your favorite soil series extents                 
### The `raster` Package  
##### `terra`       
##### `stars`
#### Importing / Exporting Rasters         
#### Object Properties     
#### Data Types   
#### Notes on Compression    
#### EXERCISE 3: getting and plotting raster data           
### Converting Vector to Raster      
### Assigning and Transforming Coordinate Systems
#### `sf`    
#### `sp` and `rgdal`           
#### `raster`      
#### Related Links
#### Interacting with `sp` Objects  
#### Coordinate Reference Systems and `proj4` Syntax 
### Accessing Spatial Data Sources via GDAL/OGR           
### Load Required Packages                                                 
### Download Example Data       
### Load the Data          
### Spatial Overlay Operations   
#### Vector Data    
#### Raster Data    
### Sampling and Extraction       
#### Raster Data Sampling                 
#### Extracting Raster Data: KSSL Pedon Locations        
#### Raster Summary By Polygon: Series Extent    
#### Raster Summary By Polygon: MLRA 
#### Faster with `exactextractr`       
### More Spatial Exploratory Data Analysis    
##### `lattice` graphics     
##### Interactive Summaries                                                                      
 
## Sampling

**Keywords:** simple random, systematic, cluster, stratified random, multistage stratified random, conditioned latin hypercube sampling, cLHS using TEUI (Terrestrial Ecological Unit Inventory) ArcGIS tool, two-stage stratified random sample design using ArcGIS

### Simple Random                                         
### Systematic                                            
### Cluster                                               
### Stratified Random                                     
### Multistage Stratified Random                          
### Conditioned Latin Hypercube (cLHS)                   
### Exercise: Design a Sampling Strategy                  
### cLHS Using TEUI                                       
### Two-Stage Stratified Random Sample Design Using ArcGIS