---
title: "Final Project"
author: "TD"
date: "January 20, 2016"
output: html_document
---
##Final Project

The final project will give you an opportunity to put the classroom experience to work with ready access to instructors. There will be ample time to work on the project during the final day of class in Lincoln. A brief document describing your project will be required for completion of the class. The broad topics below can be used as a guide in organizing the document. 

###Select a project area

Project Domain - could be confined to analysis of point data or horizons from KSSL or field descriptions, or include spatial component and resulting predictions.

Guidelines if using spatial data

Area of local interest

If you intend to work on local data with spatial data as a component of the investigation, be prepared to develop all of the associated data layers. Data needs to share a common projection, resolution, extent, GDAL format (ideally img or tiff), be modest in extent (~2,000 x 2,000 cells) and be co-registered. Ideally, this GIS work should be completed prior to the March 8th class. 

Area from the "Statistics for Soil Survey class"

If you choose to use a project area from the classroom examples, all spatial data will be provided.

###Objective(s)

Describe what you will investigate (soil properties, soil classes, both, eco-sites, etc) and the methods that will be employed.

###Results

Describe results using descriptive and graphical techniques. If predictions are used, include these.

###Discussion

Discuss how these results: 1) help in understanding the problem and 2) influence current and future investigations.

###Due Date

March 25, 2016

  


