---
title: "Final Project"
author: "Tom D'Avello, Skye Wills, and Stephen Roecker"
date: "`r Sys.Date()`"
output: html_vignette
---


The final project is intended to give you an opportunity to practice the skills covered in this course. Your mentor will be available to assist you with your project should you encounter difficulties. There should be time available during the last day of the course to begin your project. You are strongly encouraged to use your own data, but you may select one of the datasets provided during the class. Examples of previously successful projects are listed below.

Your project should follow the outline listed below, which generally represents the minimum requirement for all NASIS projects and scientific reports. Keep in mind, just because this course was taught online, doesn't mean it was intended to be any easier than say SGI, nor held to a lesser level. Projects that are incomplete will be returned with feedback, and the participants will be given another try.

- Objective or hypothesis
- Study area
- Results
- Conclusion or Discussion

Be sure to demonstrate several techniques from the part of the course you're enrolled in.

  * __Part 1:__ Use techniques from chapter 1 - 4
  * __Part 2:__ Use techniques from chapter 1 - 4 and 5 - 8. 
  

## Objective(s)

Describe the objective of your project or a hypothesis that you wish to test. Also, briefly discuss the methods that will be used. Communication is key. If you can't explain what your doing and why you're doing it, why should anyone care. It is not necessary construct an elaborate objective or hypothesis. Often small concrete examples are best. For example, comparing two similar soils or ecosites are great projects because they provide some context from which to interpret the results. Ideally most NASIS projects are intended to update SSURGO, therefore a comparison of component vs pedon data would also be productive.


## Study Area

Briefly describe the dataset you selected and the geographic setting. Be sure to include a map. 

If you plan to use spatial data, be sure to develop all of the associated data layers. Your data will need to share a common projection, resolution, extent, GDAL format (ideally img or tiff), be modest in extent (~2,000 x 2,000 cells) and be co-registered. **Ideally, use a dataset that has been prepared previously**.

If you choose to use a project area from one of the classroom examples, spatial data will be available.

If necessary, your instructor may ask for a copy of your data.


## Results

Describe your results. Include both tables and figures. Include the code used to generate your results. Provide enough information, such that someone else could duplicate your results. The most likely person to benefit from your documentation, will be the 'future' you.


## Discussion

Discuss how your results: 

   1. helped in understanding the problem,
   2. will influence current and future investigations and
   3. how do your results compare to previous work, other studies or the conventional wisdom

Focus on interpreting the results of your data and methods. Your summary need not be lengthly, but it should address the main points and your original objective or hypothesis. This is not the place to discuss the pros and cons of R, or critque the course.


## Examples

- [Example #1](http://ncss-tech.github.io/stats_for_soil_survey/chapters/10_final_project/examples/Stats_Part_1_Final_Project_-__Staggs.html)
- [Example #2](https://github.com/ncss-tech/stats_for_soil_survey/raw/master/chapters/10_final_project/examples/Statistics%20Final%20Project.docx)
- [Example #3](http://ncss-tech.github.io/stats_for_soil_survey/chapters/10_final_project/examples/Ecological_Site_Differentiation.html
)


## Due Date

February 29th, 2020


## Formatting

You can compile your final project report using several methods. Note that copying/pasting from R to Word will often corrupt code that contains single or double quotes. The R-based formats are quite simple and allow you to seamlessly combine narrative, code, output, and figures into a self-contained HTML file. [Note about reproduceable research here.](https://www.nature.com/articles/s41559-017-0160).

   * [Simple Reports from `.R` Script](https://rmarkdown.rstudio.com/articles_report_from_r_script.html)
   * [RMarkdown Documents](https://rmarkdown.rstudio.com/html_document_format.html)
   * MS Word
   
Templates:

   * [R Report Template](https://raw.githubusercontent.com/ncss-tech/stats_for_soil_survey/master/chapters/10_final_project/final-project-example.R)
   * [RMarkdown Template](https://raw.githubusercontent.com/ncss-tech/stats_for_soil_survey/master/chapters/10_final_project/final-project-example.Rmd)
   

  


