<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Tree-based Models | Statistics for Soil Survey - Part 2</title>
  <meta name="description" content="Web-based course content for Statistics for Soil Survey - Part 2 made with bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Tree-based Models | Statistics for Soil Survey - Part 2" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Web-based course content for Statistics for Soil Survey - Part 2 made with bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Tree-based Models | Statistics for Soil Survey - Part 2" />
  
  <meta name="twitter:description" content="Web-based course content for Statistics for Soil Survey - Part 2 made with bookdown::gitbook." />
  

<meta name="author" content="Soil Survey Staff" />


<meta name="date" content="2021-05-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="glm.html"/>
<link rel="next" href="acc-unc-categorical-data.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="../book/index.html">Statistics for Soil Survey - Part 1</a></li>
<li><a href="index.html">Statistics for Soil Survey - Part 2</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Pre-course Assignment</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#setup"><i class="fa fa-check"></i><b>0.1</b> Setup</a><ul>
<li class="chapter" data-level="0.1.1" data-path="index.html"><a href="index.html#create-workspace"><i class="fa fa-check"></i><b>0.1.1</b> Create Workspace</a></li>
<li class="chapter" data-level="0.1.2" data-path="index.html"><a href="index.html#configure-rstudio"><i class="fa fa-check"></i><b>0.1.2</b> Configure RStudio</a></li>
<li class="chapter" data-level="0.1.3" data-path="index.html"><a href="index.html#install-.rprofile"><i class="fa fa-check"></i><b>0.1.3</b> Install .RProfile</a></li>
<li class="chapter" data-level="0.1.4" data-path="index.html"><a href="index.html#install-required-packages"><i class="fa fa-check"></i><b>0.1.4</b> Install Required Packages</a></li>
<li class="chapter" data-level="0.1.5" data-path="index.html"><a href="index.html#common-errors"><i class="fa fa-check"></i><b>0.1.5</b> Common Errors</a></li>
<li class="chapter" data-level="0.1.6" data-path="index.html"><a href="index.html#packages-not-on-cran"><i class="fa fa-check"></i><b>0.1.6</b> Packages not on CRAN</a></li>
</ul></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#connect-to-local-nasis"><i class="fa fa-check"></i><b>0.2</b> Connect to Local NASIS</a><ul>
<li class="chapter" data-level="0.2.1" data-path="index.html"><a href="index.html#demonstrate-a-working-connection"><i class="fa fa-check"></i><b>0.2.1</b> Demonstrate a Working Connection</a></li>
</ul></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#additional-supportoptional-readings"><i class="fa fa-check"></i><b>0.3</b> Additional Support/Optional Readings</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#outline"><i class="fa fa-check"></i><b>1.1</b> Outline</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="uncertainty.html"><a href="uncertainty.html"><i class="fa fa-check"></i><b>2</b> Uncertainty</a><ul>
<li class="chapter" data-level="2.1" data-path="uncertainty.html"><a href="uncertainty.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a><ul>
<li class="chapter" data-level="2.1.1" data-path="uncertainty.html"><a href="uncertainty.html#exercise---dispersion"><i class="fa fa-check"></i><b>2.1.1</b> Exercise - Dispersion</a></li>
<li class="chapter" data-level="2.1.2" data-path="uncertainty.html"><a href="uncertainty.html#exercise---variation-and-certainty"><i class="fa fa-check"></i><b>2.1.2</b> Exercise - Variation and Certainty</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="uncertainty.html"><a href="uncertainty.html#theory-of-uncertainty"><i class="fa fa-check"></i><b>2.2</b> Theory of Uncertainty</a></li>
<li class="chapter" data-level="2.3" data-path="uncertainty.html"><a href="uncertainty.html#resampling-to-estimate-uncertainty"><i class="fa fa-check"></i><b>2.3</b> Resampling to Estimate Uncertainty</a><ul>
<li class="chapter" data-level="2.3.1" data-path="uncertainty.html"><a href="uncertainty.html#exercise---resampling"><i class="fa fa-check"></i><b>2.3.1</b> Exercise - Resampling</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="uncertainty.html"><a href="uncertainty.html#performance-metrics"><i class="fa fa-check"></i><b>2.4</b> Performance Metrics</a><ul>
<li class="chapter" data-level="2.4.1" data-path="uncertainty.html"><a href="uncertainty.html#exercise---numeric-metrics"><i class="fa fa-check"></i><b>2.4.1</b> Exercise - Numeric Metrics</a></li>
<li class="chapter" data-level="2.4.2" data-path="uncertainty.html"><a href="uncertainty.html#exercise---categorical-metrics"><i class="fa fa-check"></i><b>2.4.2</b> Exercise - Categorical Metrics</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="uncertainty.html"><a href="uncertainty.html#validation"><i class="fa fa-check"></i><b>2.5</b> Validation</a></li>
<li class="chapter" data-level="2.6" data-path="uncertainty.html"><a href="uncertainty.html#apparent-validation"><i class="fa fa-check"></i><b>2.6</b> Apparent Validation</a></li>
<li class="chapter" data-level="2.7" data-path="uncertainty.html"><a href="uncertainty.html#inherent-validation"><i class="fa fa-check"></i><b>2.7</b> Inherent Validation</a><ul>
<li class="chapter" data-level="2.7.1" data-path="uncertainty.html"><a href="uncertainty.html#split-sample---a-single-partition-of-the-data-into-a-learning-and-a-calibration-set."><i class="fa fa-check"></i><b>2.7.1</b> Split-sample - A single partition of the data into a learning and a calibration set.</a></li>
<li class="chapter" data-level="2.7.2" data-path="uncertainty.html"><a href="uncertainty.html#cross-validation---alternate-development-and-validation"><i class="fa fa-check"></i><b>2.7.2</b> Cross-validation - Alternate development and validation</a></li>
<li class="chapter" data-level="2.7.3" data-path="uncertainty.html"><a href="uncertainty.html#subsample-resampling-or-sample-simulation"><i class="fa fa-check"></i><b>2.7.3</b> Subsample (Resampling or sample simulation)</a></li>
<li class="chapter" data-level="2.7.4" data-path="uncertainty.html"><a href="uncertainty.html#external-validation"><i class="fa fa-check"></i><b>2.7.4</b> External Validation</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="uncertainty.html"><a href="uncertainty.html#additional-reading"><i class="fa fa-check"></i><b>2.8</b> Additional reading</a></li>
<li class="chapter" data-level="2.9" data-path="uncertainty.html"><a href="uncertainty.html#references-uncertainty"><i class="fa fa-check"></i><b>2.9</b> References (Uncertainty)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="numerical-tax.html"><a href="numerical-tax.html"><i class="fa fa-check"></i><b>3</b> Numerical Taxonomy and Ordination</a><ul>
<li class="chapter" data-level="3.1" data-path="numerical-tax.html"><a href="numerical-tax.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a><ul>
<li class="chapter" data-level="3.1.1" data-path="numerical-tax.html"><a href="numerical-tax.html#objectives"><i class="fa fa-check"></i><b>3.1.1</b> Objectives</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="numerical-tax.html"><a href="numerical-tax.html#whirlwind-tour"><i class="fa fa-check"></i><b>3.2</b> Whirlwind Tour</a><ul>
<li class="chapter" data-level="3.2.1" data-path="numerical-tax.html"><a href="numerical-tax.html#similarity-disimilarty-and-distance"><i class="fa fa-check"></i><b>3.2.1</b> Similarity, Disimilarty, and Distance</a></li>
<li class="chapter" data-level="3.2.2" data-path="numerical-tax.html"><a href="numerical-tax.html#standardization-of-characteristics"><i class="fa fa-check"></i><b>3.2.2</b> Standardization of Characteristics</a></li>
<li class="chapter" data-level="3.2.3" data-path="numerical-tax.html"><a href="numerical-tax.html#missing-data"><i class="fa fa-check"></i><b>3.2.3</b> Missing Data</a></li>
<li class="chapter" data-level="3.2.4" data-path="numerical-tax.html"><a href="numerical-tax.html#visualizing-pair-wise-distances-the-dendrogram"><i class="fa fa-check"></i><b>3.2.4</b> Visualizing Pair-Wise Distances: The Dendrogram</a></li>
<li class="chapter" data-level="3.2.5" data-path="numerical-tax.html"><a href="numerical-tax.html#re-arranging-a-dendrogram-for-clarity"><i class="fa fa-check"></i><b>3.2.5</b> Re-arranging a Dendrogram for Clarity</a></li>
<li class="chapter" data-level="3.2.6" data-path="numerical-tax.html"><a href="numerical-tax.html#cluster-analysis-finding-groups-in-data"><i class="fa fa-check"></i><b>3.2.6</b> Cluster Analysis: Finding Groups in Data</a></li>
<li class="chapter" data-level="3.2.7" data-path="numerical-tax.html"><a href="numerical-tax.html#ordination-visualization-in-a-reduced-space"><i class="fa fa-check"></i><b>3.2.7</b> Ordination: Visualization in a Reduced Space</a></li>
<li class="chapter" data-level="3.2.8" data-path="numerical-tax.html"><a href="numerical-tax.html#review-and-discuss-4"><i class="fa fa-check"></i><b>3.2.8</b> Review and Discuss</a></li>
<li class="chapter" data-level="3.2.9" data-path="numerical-tax.html"><a href="numerical-tax.html#pair-wise-distances-between-soil-profiles"><i class="fa fa-check"></i><b>3.2.9</b> Pair-Wise Distances Between Soil Profiles</a></li>
<li class="chapter" data-level="3.2.10" data-path="numerical-tax.html"><a href="numerical-tax.html#final-discussion"><i class="fa fa-check"></i><b>3.2.10</b> Final Discussion</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="numerical-tax.html"><a href="numerical-tax.html#excercises"><i class="fa fa-check"></i><b>3.3</b> Excercises</a><ul>
<li class="chapter" data-level="3.3.1" data-path="numerical-tax.html"><a href="numerical-tax.html#set-up-the-r-session"><i class="fa fa-check"></i><b>3.3.1</b> Set Up the R Session</a></li>
<li class="chapter" data-level="3.3.2" data-path="numerical-tax.html"><a href="numerical-tax.html#evaluating-missing-data"><i class="fa fa-check"></i><b>3.3.2</b> Evaluating Missing Data</a></li>
<li class="chapter" data-level="3.3.3" data-path="numerical-tax.html"><a href="numerical-tax.html#more-on-the-distance-matrix-and-how-to-make-one"><i class="fa fa-check"></i><b>3.3.3</b> More on the Distance Matrix and How to Make One</a></li>
<li class="chapter" data-level="3.3.4" data-path="numerical-tax.html"><a href="numerical-tax.html#hierachrical-clustering"><i class="fa fa-check"></i><b>3.3.4</b> Hierachrical Clustering</a></li>
<li class="chapter" data-level="3.3.5" data-path="numerical-tax.html"><a href="numerical-tax.html#centroid-and-medoid-partitioning-clustering-1"><i class="fa fa-check"></i><b>3.3.5</b> Centroid and Medoid (Partitioning) Clustering</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="numerical-tax.html"><a href="numerical-tax.html#practical-applications"><i class="fa fa-check"></i><b>3.4</b> Practical Applications</a><ul>
<li class="chapter" data-level="3.4.1" data-path="numerical-tax.html"><a href="numerical-tax.html#pair-wise-distances-between-soil-profiles-1"><i class="fa fa-check"></i><b>3.4.1</b> Pair-Wise Distances Between Soil Profiles</a></li>
<li class="chapter" data-level="3.4.2" data-path="numerical-tax.html"><a href="numerical-tax.html#pair-wise-distances-between-soil-series"><i class="fa fa-check"></i><b>3.4.2</b> Pair-Wise Distances Between Soil Series</a></li>
<li class="chapter" data-level="3.4.3" data-path="numerical-tax.html"><a href="numerical-tax.html#pair-wise-distances-between-subgroup-level-taxa"><i class="fa fa-check"></i><b>3.4.3</b> Pair-Wise Distances Between Subgroup-Level Taxa</a></li>
<li class="chapter" data-level="3.4.4" data-path="numerical-tax.html"><a href="numerical-tax.html#soil-color-signatures"><i class="fa fa-check"></i><b>3.4.4</b> Soil Color Signatures</a></li>
<li class="chapter" data-level="3.4.5" data-path="numerical-tax.html"><a href="numerical-tax.html#clustering-of-soil-colors"><i class="fa fa-check"></i><b>3.4.5</b> Clustering of Soil Colors</a></li>
<li class="chapter" data-level="3.4.6" data-path="numerical-tax.html"><a href="numerical-tax.html#how-do-the-interpretations-compare"><i class="fa fa-check"></i><b>3.4.6</b> “How Do the Interpretations Compare?”</a></li>
<li class="chapter" data-level="3.4.7" data-path="numerical-tax.html"><a href="numerical-tax.html#mlra-concepts-via-climate-and-elevation-samples"><i class="fa fa-check"></i><b>3.4.7</b> MLRA Concepts via Climate and Elevation Samples</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="numerical-tax.html"><a href="numerical-tax.html#references-numerical-taxonomy-and-ordination"><i class="fa fa-check"></i><b>3.5</b> References (Numerical Taxonomy and Ordination)</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="glm.html"><a href="glm.html"><i class="fa fa-check"></i><b>4</b> Generalized Linear Models</a><ul>
<li class="chapter" data-level="4.1" data-path="glm.html"><a href="glm.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="glm.html"><a href="glm.html#logistic-regression"><i class="fa fa-check"></i><b>4.2</b> Logistic Regression</a></li>
<li class="chapter" data-level="4.3" data-path="glm.html"><a href="glm.html#examples"><i class="fa fa-check"></i><b>4.3</b> Examples</a></li>
<li class="chapter" data-level="4.4" data-path="glm.html"><a href="glm.html#exercise"><i class="fa fa-check"></i><b>4.4</b> Exercise</a><ul>
<li class="chapter" data-level="4.4.1" data-path="glm.html"><a href="glm.html#load-packages"><i class="fa fa-check"></i><b>4.4.1</b> Load packages</a></li>
<li class="chapter" data-level="4.4.2" data-path="glm.html"><a href="glm.html#read-in-data"><i class="fa fa-check"></i><b>4.4.2</b> Read in data</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="glm.html"><a href="glm.html#exploratory-analysis-eda"><i class="fa fa-check"></i><b>4.5</b> Exploratory analysis (EDA)</a><ul>
<li class="chapter" data-level="4.5.1" data-path="glm.html"><a href="glm.html#data-wrangling"><i class="fa fa-check"></i><b>4.5.1</b> Data wrangling</a></li>
<li class="chapter" data-level="4.5.2" data-path="glm.html"><a href="glm.html#geomorphic-data"><i class="fa fa-check"></i><b>4.5.2</b> Geomorphic data</a></li>
<li class="chapter" data-level="4.5.3" data-path="glm.html"><a href="glm.html#soil-scientist-bias"><i class="fa fa-check"></i><b>4.5.3</b> Soil Scientist Bias</a></li>
<li class="chapter" data-level="4.5.4" data-path="glm.html"><a href="glm.html#plot-coordinates"><i class="fa fa-check"></i><b>4.5.4</b> Plot coordinates</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="glm.html"><a href="glm.html#exercise-1-view-the-data-in-arcgis"><i class="fa fa-check"></i><b>4.6</b> Exercise 1: View the data in ArcGIS</a><ul>
<li class="chapter" data-level="4.6.1" data-path="glm.html"><a href="glm.html#extracting-spatial-data"><i class="fa fa-check"></i><b>4.6.1</b> Extracting spatial data</a></li>
<li class="chapter" data-level="4.6.2" data-path="glm.html"><a href="glm.html#examine-spatial-data"><i class="fa fa-check"></i><b>4.6.2</b> Examine spatial data</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="glm.html"><a href="glm.html#constructing-the-model"><i class="fa fa-check"></i><b>4.7</b> Constructing the model</a><ul>
<li class="chapter" data-level="4.7.1" data-path="glm.html"><a href="glm.html#diagnostic"><i class="fa fa-check"></i><b>4.7.1</b> Diagnostic</a></li>
<li class="chapter" data-level="4.7.2" data-path="glm.html"><a href="glm.html#variable-selection-model-validation"><i class="fa fa-check"></i><b>4.7.2</b> Variable Selection &amp; model validation</a></li>
<li class="chapter" data-level="4.7.3" data-path="glm.html"><a href="glm.html#final-model-accuracy"><i class="fa fa-check"></i><b>4.7.3</b> Final model &amp; accuracy</a></li>
<li class="chapter" data-level="4.7.4" data-path="glm.html"><a href="glm.html#model-effects"><i class="fa fa-check"></i><b>4.7.4</b> Model effects</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="glm.html"><a href="glm.html#generate-spatial-predictions"><i class="fa fa-check"></i><b>4.8</b> Generate spatial predictions</a></li>
<li class="chapter" data-level="4.9" data-path="glm.html"><a href="glm.html#exercise-2-view-the-prediction-in-arcgis"><i class="fa fa-check"></i><b>4.9</b> Exercise 2: View the prediction in ArcGIS</a></li>
<li class="chapter" data-level="4.10" data-path="glm.html"><a href="glm.html#additional-reading-1"><i class="fa fa-check"></i><b>4.10</b> Additional reading</a></li>
<li class="chapter" data-level="4.11" data-path="glm.html"><a href="glm.html#literature-cited"><i class="fa fa-check"></i><b>4.11</b> Literature Cited</a></li>
<li class="chapter" data-level="4.12" data-path="glm.html"><a href="glm.html#references-glm"><i class="fa fa-check"></i><b>4.12</b> References (GLM)</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tree-based-models.html"><a href="tree-based-models.html"><i class="fa fa-check"></i><b>5</b> Tree-based Models</a><ul>
<li class="chapter" data-level="5.1" data-path="tree-based-models.html"><a href="tree-based-models.html#introduction-3"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="tree-based-models.html"><a href="tree-based-models.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>5.2</b> Exploratory Data Analysis</a><ul>
<li class="chapter" data-level="5.2.1" data-path="tree-based-models.html"><a href="tree-based-models.html#getting-data-into-r-and-exporting-to-shapefile"><i class="fa fa-check"></i><b>5.2.1</b> Getting Data Into R and Exporting to Shapefile</a></li>
<li class="chapter" data-level="5.2.2" data-path="tree-based-models.html"><a href="tree-based-models.html#examining-data-in-r"><i class="fa fa-check"></i><b>5.2.2</b> Examining Data in R</a></li>
<li class="chapter" data-level="5.2.3" data-path="tree-based-models.html"><a href="tree-based-models.html#exercise-1"><i class="fa fa-check"></i><b>5.2.3</b> Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="tree-based-models.html"><a href="tree-based-models.html#classification-and-regression-trees-cart"><i class="fa fa-check"></i><b>5.3</b> Classification and Regression Trees (CART)</a><ul>
<li class="chapter" data-level="5.3.1" data-path="tree-based-models.html"><a href="tree-based-models.html#exercise-2-rpart"><i class="fa fa-check"></i><b>5.3.1</b> Exercise 2: rpart</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="tree-based-models.html"><a href="tree-based-models.html#random-forest"><i class="fa fa-check"></i><b>5.4</b> Random Forest</a><ul>
<li class="chapter" data-level="5.4.1" data-path="tree-based-models.html"><a href="tree-based-models.html#exercise-3-randomforest"><i class="fa fa-check"></i><b>5.4.1</b> Exercise 3: randomForest</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="tree-based-models.html"><a href="tree-based-models.html#prediction-using-tree-based-models"><i class="fa fa-check"></i><b>5.5</b> Prediction using Tree-based Models</a></li>
<li class="chapter" data-level="5.6" data-path="tree-based-models.html"><a href="tree-based-models.html#summary"><i class="fa fa-check"></i><b>5.6</b> Summary</a></li>
<li class="chapter" data-level="5.7" data-path="tree-based-models.html"><a href="tree-based-models.html#additional-reading-2"><i class="fa fa-check"></i><b>5.7</b> Additional Reading</a></li>
<li class="chapter" data-level="5.8" data-path="tree-based-models.html"><a href="tree-based-models.html#references-tree-based-models"><i class="fa fa-check"></i><b>5.8</b> References (Tree-based Models)</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html"><i class="fa fa-check"></i><b>A</b> Accuracy and Uncertainty for Categorical Predictions</a><ul>
<li class="chapter" data-level="A.1" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#status-quo"><i class="fa fa-check"></i><b>A.1</b> Status Quo</a></li>
<li class="chapter" data-level="A.2" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#theses"><i class="fa fa-check"></i><b>A.2</b> Theses</a></li>
<li class="chapter" data-level="A.3" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#soap-box-time"><i class="fa fa-check"></i><b>A.3</b> Soap Box Time</a></li>
<li class="chapter" data-level="A.4" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#concept-demonstration-via-simulated-data"><i class="fa fa-check"></i><b>A.4</b> Concept Demonstration via Simulated Data</a></li>
<li class="chapter" data-level="A.5" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#accuracy"><i class="fa fa-check"></i><b>A.5</b> Accuracy</a><ul>
<li class="chapter" data-level="A.5.1" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#confusion-matrix-area-under-roc"><i class="fa fa-check"></i><b>A.5.1</b> Confusion Matrix / Area Under ROC</a></li>
<li class="chapter" data-level="A.5.2" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#brier-scores"><i class="fa fa-check"></i><b>A.5.2</b> Brier Scores</a></li>
<li class="chapter" data-level="A.5.3" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#tau-and-weighted-tau-class-similarity"><i class="fa fa-check"></i><b>A.5.3</b> Tau and Weighted Tau (class-similarity)</a></li>
</ul></li>
<li class="chapter" data-level="A.6" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#uncertainty-1"><i class="fa fa-check"></i><b>A.6</b> Uncertainty</a><ul>
<li class="chapter" data-level="A.6.1" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#shanon-entropy"><i class="fa fa-check"></i><b>A.6.1</b> Shanon Entropy</a></li>
</ul></li>
<li class="chapter" data-level="A.7" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#review"><i class="fa fa-check"></i><b>A.7</b> Review</a></li>
<li class="chapter" data-level="A.8" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#example-implementation"><i class="fa fa-check"></i><b>A.8</b> Example Implementation</a></li>
<li class="chapter" data-level="A.9" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#resources"><i class="fa fa-check"></i><b>A.9</b> Resources</a><ul>
<li class="chapter" data-level="A.9.1" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#evaluating-accuracy-of-categorical-probabilistic-predictions"><i class="fa fa-check"></i><b>A.9.1</b> Evaluating Accuracy of Categorical / Probabilistic Predictions</a></li>
<li class="chapter" data-level="A.9.2" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#sampling-and-stability-of-estimates"><i class="fa fa-check"></i><b>A.9.2</b> Sampling and Stability of Estimates</a></li>
</ul></li>
<li class="chapter" data-level="A.10" data-path="acc-unc-categorical-data.html"><a href="acc-unc-categorical-data.html#references-class-accuracy-uncertainty"><i class="fa fa-check"></i><b>A.10</b> References (Class Accuracy / Uncertainty)</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="commentary-selecting-a-modeling-framework.html"><a href="commentary-selecting-a-modeling-framework.html"><i class="fa fa-check"></i><b>B</b> Commentary: Selecting a Modeling Framework</a><ul>
<li class="chapter" data-level="B.1" data-path="commentary-selecting-a-modeling-framework.html"><a href="commentary-selecting-a-modeling-framework.html#soil-temperature-regime-modeling-in-ca792"><i class="fa fa-check"></i><b>B.1</b> Soil Temperature Regime Modeling in CA792</a></li>
<li class="chapter" data-level="B.2" data-path="commentary-selecting-a-modeling-framework.html"><a href="commentary-selecting-a-modeling-framework.html#references-modeling-frameworks"><i class="fa fa-check"></i><b>B.2</b> References (Modeling Frameworks)</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics for Soil Survey - Part 2</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tree-based-models" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Tree-based Models</h1>
<div class="figure">
<img src="static-figures/logo.jpg" alt="" />
<p class="caption">Statistics for pedologists course banner image</p>
</div>
<div id="introduction-3" class="section level2">
<h2><span class="header-section-number">5.1</span> Introduction</h2>
<p>Tree-based models are a supervised machine learning method commonly used in soil survey and ecology for exploratory data analysis and prediction due to their simplistic nonparametric design. Instead of fitting a model to the data, tree-based models recursively partition the data into increasingly homogenous groups based on values that minimize a loss function (such as Sum of Squared Errors (SSE) for regression or Gini Index for classification) (<a href="http://www.clw.csiro.au/aclep/documents/McBratney%20et%20al.%202003.pdf">McBratney et al.,2013</a>). The two most common packages for generating tree-based models in R are rpart and randomForest. The rpart package creates a regression or classification tree based on binary splits that maximize homogeneity and minimize impurity. The output is a single decision tree that can be further “pruned” or trimmed back using the cross-validation error statistic to reduce over-fitting. The randomForest package is similar to rpart, but is double random in that each node is split using a random subset of predictors AND observations at each node and this process is repeated hundreds of times (as specified by the user). Unlike rpart, random forests do not produce a graphical decision tree since the predictions are averaged across hundreds or thousands of trees. Instead, random forests produce a variable importance plot and a tabular statistical summary.</p>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2><span class="header-section-number">5.2</span> Exploratory Data Analysis</h2>
<p>The data that we will be working with in this chapter were collected in support of a MLRA 127 soil survey update project to tabularly and spatially update SSRUGO map units for spodic properties in the Monongahela National Forest. Soils that were historically covered by Eastern Hemlock and Red Spruce exhibit spodic morphology on shale, siltstone, and sandstone bedrocks at elevations typically &gt;3,200 ft in West Virginia (<a href="http://www.sciencedirect.com/science/article/pii/S0016706115000427">Nauman et al., 2015</a>). The landscape and vegetative communities were greatly altered by fire and logging in the early 1900s, complicating the identification of spodic morphology. It is of particular interest to the project leader and the U.S. Forest Service that spatial maps be developed to depict the location of spodic morphology and folistic epipedons in the Monongahela National Forest. Folistic epipedons provide habitat for the Northern Flying Squirrel, just recently removed from the endangered species list.</p>
<div id="getting-data-into-r-and-exporting-to-shapefile" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Getting Data Into R and Exporting to Shapefile</h3>
<p>Before we dive in to model building, let’s first import and plot the dataset in R.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="tree-based-models.html#cb166-1"></a><span class="kw">library</span>(lattice) <span class="co">#graphing</span></span>
<span id="cb166-2"><a href="tree-based-models.html#cb166-2"></a><span class="kw">library</span>(sp) <span class="co">#spatial data</span></span>
<span id="cb166-3"><a href="tree-based-models.html#cb166-3"></a><span class="kw">library</span>(maps) <span class="co">#maps</span></span>
<span id="cb166-4"><a href="tree-based-models.html#cb166-4"></a><span class="kw">library</span>(rgdal) <span class="co">#spatial import</span></span>
<span id="cb166-5"><a href="tree-based-models.html#cb166-5"></a><span class="kw">library</span>(corrplot) <span class="co">#graphical display of correlation matrix</span></span>
<span id="cb166-6"><a href="tree-based-models.html#cb166-6"></a></span>
<span id="cb166-7"><a href="tree-based-models.html#cb166-7"></a>file &lt;-<span class="st">&#39;https://raw.githubusercontent.com/ncss-tech/stats_for_soil_survey/master/data/logistic/wv_transect_editedforR.csv&#39;</span></span>
<span id="cb166-8"><a href="tree-based-models.html#cb166-8"></a><span class="kw">download.file</span>(file, <span class="dt">destfile =</span> <span class="st">&quot;soildata.csv&quot;</span>)</span>
<span id="cb166-9"><a href="tree-based-models.html#cb166-9"></a>soildata &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;soildata.csv&quot;</span>, <span class="dt">header=</span><span class="ot">TRUE</span>, <span class="dt">sep=</span><span class="st">&quot;,&quot;</span>)</span>
<span id="cb166-10"><a href="tree-based-models.html#cb166-10"></a><span class="kw">coordinates</span>(soildata) &lt;-<span class="st"> </span><span class="er">~</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span>y <span class="co">#set the coordinates; converting dataframe to a spatial object</span></span>
<span id="cb166-11"><a href="tree-based-models.html#cb166-11"></a><span class="kw">proj4string</span>(soildata) &lt;-<span class="st"> </span><span class="kw">CRS</span>(<span class="st">&quot;+init=EPSG:4269&quot;</span>) <span class="co">#set the projection; https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/OverviewCoordinateReferenceSystems.pdf </span></span>
<span id="cb166-12"><a href="tree-based-models.html#cb166-12"></a></span>
<span id="cb166-13"><a href="tree-based-models.html#cb166-13"></a><span class="kw">map</span>(<span class="st">&quot;county&quot;</span>, <span class="st">&quot;west virginia&quot;</span>) </span>
<span id="cb166-14"><a href="tree-based-models.html#cb166-14"></a><span class="kw">points</span>(soildata) <span class="co">#plot points</span></span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="tree-based-models.html#cb167-1"></a><span class="co">#convert soildata into a shapefile</span></span>
<span id="cb167-2"><a href="tree-based-models.html#cb167-2"></a><span class="kw">writeOGR</span>(soildata, <span class="dt">dsn =</span> <span class="st">&quot;C:/workspace&quot;</span>, <span class="st">&quot;soildata&quot;</span>, <span class="dt">driver =</span> <span class="st">&quot;ESRI Shapefile&quot;</span>) </span></code></pre></div>
<p>Conveniently, environmental covariate values were previously extracted for all of the observations in the <strong>soildata</strong> dataset. <strong>How would you extract raster data to points in R?</strong> (<a href="https://github.com/ncss-tech/stats_for_soil_survey/blob/master/chapters/6_linear_models/6_Linear_models.md">Hint</a>)</p>
</div>
<div id="examining-data-in-r" class="section level3">
<h3><span class="header-section-number">5.2.2</span> Examining Data in R</h3>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="tree-based-models.html#cb168-1"></a><span class="co">#since we converted the soildata dataframe to a spatial object to export as a shapefile, we will need to convert it back to a dataframe to plot and further examine the data in R</span></span>
<span id="cb168-2"><a href="tree-based-models.html#cb168-2"></a></span>
<span id="cb168-3"><a href="tree-based-models.html#cb168-3"></a><span class="co">#re-importing the data and overwriting the soildata object is just one way to achieve this</span></span>
<span id="cb168-4"><a href="tree-based-models.html#cb168-4"></a>file &lt;-<span class="st">&#39;https://raw.githubusercontent.com/ncss-tech/stats_for_soil_survey/master/data/logistic/wv_transect_editedforR.csv&#39;</span></span>
<span id="cb168-5"><a href="tree-based-models.html#cb168-5"></a><span class="kw">download.file</span>(file, <span class="dt">destfile =</span> <span class="st">&quot;soildata.csv&quot;</span>)</span>
<span id="cb168-6"><a href="tree-based-models.html#cb168-6"></a>soildata &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;soildata.csv&quot;</span>, <span class="dt">header=</span><span class="ot">TRUE</span>, <span class="dt">sep=</span><span class="st">&quot;,&quot;</span>)</span>
<span id="cb168-7"><a href="tree-based-models.html#cb168-7"></a><span class="kw">View</span>(soildata) <span class="co">#view the data</span></span>
<span id="cb168-8"><a href="tree-based-models.html#cb168-8"></a><span class="kw">str</span>(soildata) <span class="co">#examine the internal data structure</span></span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    250 obs. of  50 variables:
##  $ x           : num  -79.7 -79.7 -79.7 -79.8 -79.7 ...
##  $ y           : num  38.6 38.6 38.6 38.6 38.6 ...
##  $ Overtype    : chr  &quot;Hardwood&quot; &quot;Hardwood&quot; &quot;Hardwood&quot; &quot;Hardwood&quot; ...
##  $ Underconifer: chr  &quot;n&quot; &quot;y&quot; &quot;n&quot; &quot;y&quot; ...
##  $ Oi          : num  3 4 3 4 3 2 2 2 4 3 ...
##  $ Oe          : num  0 0 2 4 4 6 4 2 2 4 ...
##  $ Oa          : num  0 3 0 0 8 0 0 0 7 4 ...
##  $ Otot        : num  3 7 5 8 15 8 6 4 13 7 ...
##  $ epipedon    : chr  &quot;ochric&quot; &quot;ochric&quot; &quot;ochric&quot; &quot;ochric&quot; ...
##  $ spodint     : num  0 0 0 0 1 1 1 0.5 1 0 ...
##  $ subgroup    : chr  &quot;typic&quot; &quot;typic&quot; &quot;typic&quot; &quot;typic&quot; ...
##  $ order       : chr  &quot;ultisol&quot; &quot;inceptisol&quot; &quot;ultisol&quot; &quot;inceptisol&quot; ...
##  $ ps          : chr  &quot;fl&quot; &quot;ls&quot; &quot;fl&quot; &quot;cl&quot; ...
##  $ drainage    : chr  &quot;wd&quot; &quot;wd&quot; &quot;wd&quot; &quot;wd&quot; ...
##  $ series      : chr  &quot;Carrollton&quot; &quot;Mandy&quot; &quot;Carrollton&quot; &quot;Mandy&quot; ...
##  $ taxon       : chr  &quot;series&quot; &quot;series&quot; &quot;series&quot; &quot;taxadjunct&quot; ...
##  $ slope       : int  45 54 39 25 38 30 38 36 16 36 ...
##  $ surfacetex  : chr  &quot;l&quot; &quot;l&quot; &quot;cnl&quot; &quot;l&quot; ...
##  $ stoniness   : chr  &quot;stx&quot; &quot;stv&quot; &quot;stx&quot; &quot;stv&quot; ...
##  $ depthclass  : chr  &quot;md&quot; &quot;md&quot; &quot;md&quot; &quot;md&quot; ...
##  $ bedrockdepth: int  200 200 200 200 200 200 200 200 200 200 ...
##  $ depth_cm    : int  67 69 52 95 93 81 86 90 75 92 ...
##  $ hillslope   : chr  &quot;backslope&quot; &quot;backslope&quot; &quot;backslope&quot; &quot;backslope&quot; ...
##  $ tipmound    : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ rainfall    : int  51 51 51 51 51 51 51 51 51 51 ...
##  $ geology     : chr  &quot;Dch&quot; &quot;Dhs&quot; &quot;Dhs&quot; &quot;Dhs&quot; ...
##  $ aachn       : num  27.46 81.7 2.59 43.36 70.75 ...
##  $ dem10m      : num  1123 1239 1155 1240 1211 ...
##  $ downslpgra  : num  25.9 25.1 78 37 26.1 ...
##  $ eastness    : num  -0.53 0.972 1 0.9 -0.474 ...
##  $ greenrefl   : num  0.1035 0.0425 0.0351 0.0776 0.0721 ...
##  $ landsatb1   : num  0.0726 0.0742 0.0742 0.0775 0.0694 ...
##  $ landsatb2   : num  0.062 0.0583 0.0547 0.0583 0.0528 ...
##  $ landsatb3   : num  0.0335 0.0351 0.0301 0.0419 0.0318 ...
##  $ landsatb7   : num  0.0494 0.0516 0.043 0.0451 0.0302 ...
##  $ maxc100     : num  -0.0845 -0.0963 -0.0848 0.2386 0.1368 ...
##  $ maxent      : num  20.26 30.21 27.44 7.88 73.85 ...
##  $ minc100     : num  -0.1925 -0.1457 -0.8324 0.069 0.0998 ...
##  $ mirref      : num  0.1608 0.0827 0.1109 0.1477 0.0762 ...
##  $ ndvi        : num  0.866 0.822 0.842 0.8 0.77 ...
##  $ northeastn  : num  -0.974 0.854 0.728 0.944 -0.958 ...
##  $ northness   : num  -0.848 0.237 0.03 0.435 -0.88 ...
##  $ northwestn  : num  -0.225 -0.52 -0.686 -0.329 -0.287 ...
##  $ planc100    : num  -0.1177 -0.1077 -0.2173 0.1321 0.0476 ...
##  $ proc100     : num  -0.231 -0.178 -0.735 0.221 0.161 ...
##  $ protection  : num  0.237 0.154 0.222 0.114 0.138 ...
##  $ relpos11    : num  0.352 0.507 0.233 0.544 0.585 ...
##  $ slp50       : num  42.4 42.3 26.3 24.5 36.3 ...
##  $ solar       : int  1481510 1280610 1348160 1322630 1532160 1536340 1488440 1155820 1440500 1474730 ...
##  $ tanc75      : num  0.0511 0.0279 0.0553 -0.0187 -0.0346 ...</code></pre>
<p>The example dataset, <strong>soildata</strong>, consists of 250 observations and 58 variables that were collected in the field or derived from geospatial data to identify spodic soil properties in West Virginia. Of particular interest is determining best splits for spodic intensity (relative spodicity index). As you can see in the data structure, R interpreted the spodint field as numeric. Since spodint is an index, it will need to be changed to a factor and then to an ordered factor. The same will need to be done for tipmound (a tip and mound microtopography index).</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="tree-based-models.html#cb170-1"></a><span class="kw">set.seed</span>(<span class="dv">250</span>)</span>
<span id="cb170-2"><a href="tree-based-models.html#cb170-2"></a>soildata<span class="op">$</span>spodint &lt;-<span class="st"> </span><span class="kw">as.factor</span>(soildata<span class="op">$</span>spodint)</span>
<span id="cb170-3"><a href="tree-based-models.html#cb170-3"></a>soildata<span class="op">$</span>spodint &lt;-<span class="st"> </span><span class="kw">ordered</span>(soildata<span class="op">$</span>spodint)</span>
<span id="cb170-4"><a href="tree-based-models.html#cb170-4"></a>soildata<span class="op">$</span>tipmound &lt;-<span class="st"> </span><span class="kw">as.factor</span>(soildata<span class="op">$</span>tipmound)</span>
<span id="cb170-5"><a href="tree-based-models.html#cb170-5"></a>soildata<span class="op">$</span>tipmound &lt;-<span class="st"> </span><span class="kw">ordered</span>(soildata<span class="op">$</span>tipmound)</span></code></pre></div>
<p>Next, let’s explore the tabular data:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="tree-based-models.html#cb171-1"></a><span class="kw">boxplot</span>(solar<span class="op">~</span>spodint, <span class="dt">data=</span>soildata, <span class="dt">xlab=</span><span class="st">&quot;spodic intensity&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;solar&quot;</span>) <span class="co">#does solar radiation affect spodic intensity?</span></span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="tree-based-models.html#cb172-1"></a><span class="kw">boxplot</span>(northwestn<span class="op">~</span>spodint, <span class="dt">data=</span>soildata, <span class="dt">xlab=</span><span class="st">&quot;spodic intensity&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;northwestness&quot;</span>) <span class="co">#how about aspect?</span></span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="tree-based-models.html#cb173-1"></a><span class="kw">densityplot</span>(<span class="op">~</span><span class="st"> </span>Otot<span class="op">|</span>order, <span class="dt">data=</span>soildata) <span class="co">#distribution of O horizon thickness among soil orders</span></span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-5-3.png" width="672" /></p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="tree-based-models.html#cb174-1"></a>numeric &lt;-<span class="st"> </span><span class="kw">data.frame</span>(soildata[, <span class="kw">c</span>(<span class="dv">8</span>, <span class="dv">25</span>, <span class="dv">27</span><span class="op">:</span><span class="dv">50</span>)]) <span class="co">#combine numeric columns into a new data frame</span></span>
<span id="cb174-2"><a href="tree-based-models.html#cb174-2"></a><span class="kw">names</span>(numeric) </span></code></pre></div>
<pre><code>##  [1] &quot;Otot&quot;       &quot;rainfall&quot;   &quot;aachn&quot;      &quot;dem10m&quot;     &quot;downslpgra&quot;
##  [6] &quot;eastness&quot;   &quot;greenrefl&quot;  &quot;landsatb1&quot;  &quot;landsatb2&quot;  &quot;landsatb3&quot; 
## [11] &quot;landsatb7&quot;  &quot;maxc100&quot;    &quot;maxent&quot;     &quot;minc100&quot;    &quot;mirref&quot;    
## [16] &quot;ndvi&quot;       &quot;northeastn&quot; &quot;northness&quot;  &quot;northwestn&quot; &quot;planc100&quot;  
## [21] &quot;proc100&quot;    &quot;protection&quot; &quot;relpos11&quot;   &quot;slp50&quot;      &quot;solar&quot;     
## [26] &quot;tanc75&quot;</code></pre>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="tree-based-models.html#cb176-1"></a>cormatrix &lt;-<span class="st"> </span><span class="kw">cor</span>(numeric) <span class="co">#calculate correlation matrix</span></span>
<span id="cb176-2"><a href="tree-based-models.html#cb176-2"></a><span class="kw">corrplot</span>(cormatrix, <span class="dt">method =</span> <span class="st">&quot;circle&quot;</span>) <span class="co">#plot correlation matrix</span></span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-5-4.png" width="672" /></p>
</div>
<div id="exercise-1" class="section level3">
<h3><span class="header-section-number">5.2.3</span> Exercise 1</h3>
<p>Examine the <strong>soildata</strong> shapefile and environmental covariate data in ArcGIS. Come up with a theory of which possible covariates might be useful for predicting spodic morphology and folistic epipedons. Also, think of the different possible ways to model these features given the <strong>soildata</strong> dataset.</p>
</div>
</div>
<div id="classification-and-regression-trees-cart" class="section level2">
<h2><span class="header-section-number">5.3</span> Classification and Regression Trees (CART)</h2>
<p>The basic form for all CART models is (y ~ x), where y is the dependent variable to be predicted from x, a set of independent variables. If the dependent variable (y) is numeric, the resulting tree will be a regression tree. Conversely, if the dependent variable (y) is categorical, the resulting tree will be a classification tree. The rpart package allows all data types to be used as independent variables, regardless of whether the model is a classification or regression tree. The rpart algorithm ignores missing values when determining the quality of a split and uses surrogate splits to determine if observation(s) with missing data is best split left or right. If an observation is missing all surrogate splits, then the observation(s) is sent to the child node with the largest relative frequency (Feelders, 1999).</p>
<p>Assuming that the rpart and randomForest packages are already installed on your machine, simply load the packages using the <code>library()</code> function.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="tree-based-models.html#cb177-1"></a><span class="kw">library</span>(rpart) <span class="co">#CART models</span></span>
<span id="cb177-2"><a href="tree-based-models.html#cb177-2"></a><span class="kw">library</span>(randomForest) <span class="co">#random forest</span></span>
<span id="cb177-3"><a href="tree-based-models.html#cb177-3"></a><span class="kw">library</span>(rpart.plot) <span class="co">#rpart plot graphics</span></span>
<span id="cb177-4"><a href="tree-based-models.html#cb177-4"></a><span class="kw">library</span>(caret) <span class="co">#confusion matrix</span></span></code></pre></div>
<p>If you wanted to create a classification tree for spodint using all of the variables, you would simply type: <code>rpart(spodint ~ ., data=soildata)</code>. Since our goal is to generate a spatial prediction model, we only want to use the variables for which we have spatial coverage–our environmental covariate rasters.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="tree-based-models.html#cb178-1"></a>spodintmodel &lt;-<span class="st"> </span><span class="kw">rpart</span>(spodint <span class="op">~</span><span class="st"> </span>rainfall <span class="op">+</span><span class="st"> </span>geology <span class="op">+</span><span class="st"> </span>aachn <span class="op">+</span><span class="st"> </span>dem10m <span class="op">+</span><span class="st"> </span>downslpgra <span class="op">+</span><span class="st"> </span>eastness <span class="op">+</span><span class="st"> </span>greenrefl <span class="op">+</span><span class="st"> </span>landsatb1 <span class="op">+</span><span class="st"> </span>landsatb2 <span class="op">+</span><span class="st"> </span>landsatb3 <span class="op">+</span>landsatb7 <span class="op">+</span><span class="st"> </span>maxc100 <span class="op">+</span><span class="st"> </span>maxent <span class="op">+</span><span class="st"> </span>minc100 <span class="op">+</span><span class="st"> </span>mirref <span class="op">+</span><span class="st"> </span>ndvi<span class="op">+</span><span class="st"> </span>northeastn <span class="op">+</span><span class="st"> </span>northness <span class="op">+</span><span class="st"> </span>northwestn <span class="op">+</span><span class="st"> </span>planc100 <span class="op">+</span><span class="st"> </span>proc100 <span class="op">+</span><span class="st"> </span>protection <span class="op">+</span><span class="st"> </span>relpos11 <span class="op">+</span><span class="st"> </span>slp50 <span class="op">+</span><span class="st"> </span>solar <span class="op">+</span><span class="st"> </span>tanc75, <span class="dt">data =</span> soildata, <span class="dt">method =</span> <span class="st">&quot;class&quot;</span>)</span>
<span id="cb178-2"><a href="tree-based-models.html#cb178-2"></a></span>
<span id="cb178-3"><a href="tree-based-models.html#cb178-3"></a>spodintmodel</span></code></pre></div>
<pre><code>## n= 250 
## 
## node), split, n, loss, yval, (yprob)
##       * denotes terminal node
## 
##   1) root 250 162 0 (0.35 0.084 0.26 0.024 0.28)  
##     2) northwestn&lt; 0.55138 148  80 0 (0.46 0.081 0.29 0.027 0.14)  
##       4) maxc100&lt; 0.10341 57  20 0 (0.65 0.088 0.14 0.018 0.11) *
##       5) maxc100&gt;=0.10341 91  56 1 (0.34 0.077 0.38 0.033 0.16)  
##        10) solar&lt; 1504355 83  52 0 (0.37 0.084 0.33 0.036 0.18)  
##          20) minc100&lt; -0.197089 9   1 0 (0.89 0 0 0 0.11) *
##          21) minc100&gt;=-0.197089 74  47 1 (0.31 0.095 0.36 0.041 0.19)  
##            42) maxent&lt; 12.9024 23  10 0 (0.57 0.13 0.26 0.043 0)  
##              84) solar&lt; 1460005 16   5 0 (0.69 0.19 0.12 0 0) *
##              85) solar&gt;=1460005 7   3 1 (0.29 0 0.57 0.14 0) *
##            43) maxent&gt;=12.9024 51  30 1 (0.2 0.078 0.41 0.039 0.27)  
##              86) greenrefl&gt;=0.01846795 40  20 1 (0.22 0.075 0.5 0.025 0.17)  
##               172) dem10m&gt;=1012.96 33  14 1 (0.27 0.061 0.58 0 0.091)  
##                 344) minc100&lt; 0.06651935 24   7 1 (0.21 0.083 0.71 0 0) *
##                 345) minc100&gt;=0.06651935 9   5 0 (0.44 0 0.22 0 0.33) *
##               173) dem10m&lt; 1012.96 7   3 2 (0 0.14 0.14 0.14 0.57) *
##              87) greenrefl&lt; 0.01846795 11   4 2 (0.091 0.091 0.091 0.091 0.64) *
##        11) solar&gt;=1504355 8   0 1 (0 0 1 0 0) *
##     3) northwestn&gt;=0.55138 102  53 2 (0.2 0.088 0.22 0.02 0.48)  
##       6) protection&lt; 0.0988242 25  15 1 (0.2 0.16 0.4 0.04 0.2)  
##        12) proc100&lt; 0.1502945 14  10 0 (0.29 0.29 0.14 0 0.29) *
##        13) proc100&gt;=0.1502945 11   3 1 (0.091 0 0.73 0.091 0.091) *
##       7) protection&gt;=0.0988242 77  33 2 (0.19 0.065 0.16 0.013 0.57)  
##        14) maxent&lt; 9.5806 30  19 0 (0.37 0.1 0.17 0.033 0.33)  
##          28) rainfall&lt; 52 9   2 0 (0.78 0 0 0 0.22) *
##          29) rainfall&gt;=52 21  13 2 (0.19 0.14 0.24 0.048 0.38)  
##            58) landsatb7&gt;=0.0398039 12   7 1 (0.17 0.25 0.42 0 0.17) *
##            59) landsatb7&lt; 0.0398039 9   3 2 (0.22 0 0 0.11 0.67) *
##        15) maxent&gt;=9.5806 47  13 2 (0.085 0.043 0.15 0 0.72) *</code></pre>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="tree-based-models.html#cb180-1"></a><span class="kw">plot</span>(spodintmodel)</span>
<span id="cb180-2"><a href="tree-based-models.html#cb180-2"></a><span class="kw">text</span>(spodintmodel, <span class="dt">cex=</span><span class="fl">0.8</span>) <span class="co">#cex is text size</span></span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="tree-based-models.html#cb181-1"></a><span class="co">#if you are having trouble viewing the text in the plot window, click zoom to open a bigger window</span></span>
<span id="cb181-2"><a href="tree-based-models.html#cb181-2"></a><span class="co">#you may also need to adjust the plot margins or text size; for this example, try:</span></span>
<span id="cb181-3"><a href="tree-based-models.html#cb181-3"></a><span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">3</span>,<span class="dv">6</span>)) </span>
<span id="cb181-4"><a href="tree-based-models.html#cb181-4"></a><span class="kw">plot</span>(spodintmodel)</span>
<span id="cb181-5"><a href="tree-based-models.html#cb181-5"></a><span class="kw">text</span>(spodintmodel, <span class="dt">cex=</span><span class="fl">0.6</span>)</span></code></pre></div>
<p>For more plot customization, use the rpart.plot package.</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="tree-based-models.html#cb182-1"></a><span class="kw">rpart.plot</span>(spodintmodel, <span class="dt">extra=</span><span class="dv">3</span>) <span class="co">#extra=3 displays the misclassification rate at the node, expressed as the number of incorrect classifications divided by the total observations in the node; there are many options under the extra setting for classification models</span></span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-9-1.png" width="576" /></p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="tree-based-models.html#cb183-1"></a><span class="kw">rpart.plot</span>(spodintmodel, <span class="dt">extra=</span><span class="dv">103</span>) <span class="co">#adding 100 to the extra setting displays the percentage observations in the node</span></span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-9-2.png" width="576" /></p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="tree-based-models.html#cb184-1"></a><span class="kw">prp</span>(spodintmodel,<span class="dt">type=</span><span class="dv">1</span>,<span class="dt">extra=</span><span class="dv">1</span>,<span class="dt">branch=</span><span class="dv">1</span>) <span class="co">#prp is another function in the rpart.plot package that has numerous plot customization options</span></span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-9-3.png" width="576" /></p>
<p>Notice that the terminal nodes display the different spodic intensity classes, ranging from 0 to 2. <strong>Can you think of another way that we could model spodic expression?</strong></p>
<p>Could we treat spodic intesity (an ordered factor) as numeric, ranging from 0 to 1 to develop a regression tree? Does this make sense? what would a mean of 1 tell you about the observations in the terminal node?</p>
<p>What if we considered everything with a spodic intensity of &lt;= 0.5 to be non-spodic and everything &gt;0.5 to be spodic? A binary probability approach to predicting spodic morphology, similar to Nauman et al., 2015.</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="tree-based-models.html#cb185-1"></a>index &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="fl">1.5</span>, <span class="dv">2</span>) <span class="co">#index for lookup table</span></span>
<span id="cb185-2"><a href="tree-based-models.html#cb185-2"></a>values &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;nonspodic&quot;</span>, <span class="st">&quot;nonspodic&quot;</span>, <span class="st">&quot;spodic&quot;</span>, <span class="st">&quot;spodic&quot;</span>, <span class="st">&quot;spodic&quot;</span>) <span class="co">#assigning corresponding categories to look up values</span></span>
<span id="cb185-3"><a href="tree-based-models.html#cb185-3"></a>soildata<span class="op">$</span>newcolumn &lt;-<span class="st"> </span>values[<span class="kw">match</span>(soildata<span class="op">$</span>spodint, index)] <span class="co">#match spodint to index and assign values</span></span>
<span id="cb185-4"><a href="tree-based-models.html#cb185-4"></a>soildata<span class="op">$</span>newcolumn &lt;-<span class="st"> </span><span class="kw">as.factor</span>(soildata<span class="op">$</span>newcolumn) <span class="co">#convert new column from character to factor</span></span>
<span id="cb185-5"><a href="tree-based-models.html#cb185-5"></a></span>
<span id="cb185-6"><a href="tree-based-models.html#cb185-6"></a>spodintmodel2 &lt;-<span class="st"> </span><span class="kw">rpart</span>(newcolumn <span class="op">~</span><span class="st"> </span>rainfall <span class="op">+</span><span class="st"> </span>geology <span class="op">+</span><span class="st"> </span>aachn <span class="op">+</span><span class="st"> </span>dem10m <span class="op">+</span><span class="st"> </span>downslpgra <span class="op">+</span><span class="st"> </span>eastness <span class="op">+</span><span class="st"> </span>greenrefl <span class="op">+</span><span class="st"> </span>landsatb1 <span class="op">+</span><span class="st"> </span>landsatb2 <span class="op">+</span><span class="st"> </span>landsatb3 <span class="op">+</span>landsatb7 <span class="op">+</span><span class="st"> </span>maxc100 <span class="op">+</span><span class="st"> </span>maxent <span class="op">+</span><span class="st"> </span>minc100 <span class="op">+</span><span class="st"> </span>mirref <span class="op">+</span><span class="st"> </span>ndvi<span class="op">+</span><span class="st"> </span>northeastn <span class="op">+</span><span class="st"> </span>northness <span class="op">+</span><span class="st"> </span>northwestn <span class="op">+</span><span class="st"> </span>planc100 <span class="op">+</span><span class="st"> </span>proc100 <span class="op">+</span><span class="st"> </span>protection <span class="op">+</span><span class="st"> </span>relpos11 <span class="op">+</span><span class="st"> </span>slp50 <span class="op">+</span><span class="st"> </span>solar <span class="op">+</span><span class="st"> </span>tanc75, <span class="dt">data =</span> soildata, <span class="dt">method =</span> <span class="st">&quot;class&quot;</span>)</span>
<span id="cb185-7"><a href="tree-based-models.html#cb185-7"></a></span>
<span id="cb185-8"><a href="tree-based-models.html#cb185-8"></a>spodintmodel2</span></code></pre></div>
<pre><code>## n= 250 
## 
## node), split, n, loss, yval, (yprob)
##       * denotes terminal node
## 
##  1) root 250 109 spodic (0.4360000 0.5640000)  
##    2) eastness&gt;=-0.1275925 100  36 nonspodic (0.6400000 0.3600000)  
##      4) tanc75&gt;=-0.0268239 64  16 nonspodic (0.7500000 0.2500000) *
##      5) tanc75&lt; -0.0268239 36  16 spodic (0.4444444 0.5555556)  
##       10) northeastn&gt;=0.7433605 13   3 nonspodic (0.7692308 0.2307692) *
##       11) northeastn&lt; 0.7433605 23   6 spodic (0.2608696 0.7391304) *
##    3) eastness&lt; -0.1275925 150  45 spodic (0.3000000 0.7000000)  
##      6) minc100&lt; -0.1576455 47  23 spodic (0.4893617 0.5106383)  
##       12) dem10m&gt;=1054.305 15   2 nonspodic (0.8666667 0.1333333) *
##       13) dem10m&lt; 1054.305 32  10 spodic (0.3125000 0.6875000)  
##         26) protection&gt;=0.178847 13   5 nonspodic (0.6153846 0.3846154) *
##         27) protection&lt; 0.178847 19   2 spodic (0.1052632 0.8947368) *
##      7) minc100&gt;=-0.1576455 103  22 spodic (0.2135922 0.7864078)  
##       14) landsatb7&gt;=0.0440802 37  15 spodic (0.4054054 0.5945946)  
##         28) planc100&lt; -0.00902005 8   1 nonspodic (0.8750000 0.1250000) *
##         29) planc100&gt;=-0.00902005 29   8 spodic (0.2758621 0.7241379) *
##       15) landsatb7&lt; 0.0440802 66   7 spodic (0.1060606 0.8939394) *</code></pre>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="tree-based-models.html#cb187-1"></a><span class="kw">plot</span>(spodintmodel2)</span>
<span id="cb187-2"><a href="tree-based-models.html#cb187-2"></a><span class="kw">text</span>(spodintmodel2, <span class="dt">cex=</span><span class="fl">0.8</span>)</span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Notice that several of the splits changed. Which model performed better? One way to compare the two models is to use the function <code>printcp()</code>:</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="tree-based-models.html#cb188-1"></a><span class="kw">printcp</span>(spodintmodel)</span></code></pre></div>
<pre><code>## 
## Classification tree:
## rpart(formula = spodint ~ rainfall + geology + aachn + dem10m + 
##     downslpgra + eastness + greenrefl + landsatb1 + landsatb2 + 
##     landsatb3 + landsatb7 + maxc100 + maxent + minc100 + mirref + 
##     ndvi + northeastn + northness + northwestn + planc100 + proc100 + 
##     protection + relpos11 + slp50 + solar + tanc75, data = soildata, 
##     method = &quot;class&quot;)
## 
## Variables actually used in tree construction:
##  [1] dem10m     greenrefl  landsatb7  maxc100    maxent     minc100   
##  [7] northwestn proc100    protection rainfall   solar     
## 
## Root node error: 162/250 = 0.648
## 
## n= 250 
## 
##         CP nsplit rel error  xerror     xstd
## 1 0.179012      0   1.00000 1.00000 0.046614
## 2 0.030864      1   0.82099 0.90123 0.048107
## 3 0.029321      2   0.79012 0.91358 0.047967
## 4 0.018519      7   0.63580 0.95679 0.047374
## 5 0.015432      8   0.61728 0.94444 0.047561
## 6 0.012346     11   0.56790 0.94444 0.047561
## 7 0.010000     14   0.53086 0.95679 0.047374</code></pre>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="tree-based-models.html#cb190-1"></a><span class="kw">printcp</span>(spodintmodel2)</span></code></pre></div>
<pre><code>## 
## Classification tree:
## rpart(formula = newcolumn ~ rainfall + geology + aachn + dem10m + 
##     downslpgra + eastness + greenrefl + landsatb1 + landsatb2 + 
##     landsatb3 + landsatb7 + maxc100 + maxent + minc100 + mirref + 
##     ndvi + northeastn + northness + northwestn + planc100 + proc100 + 
##     protection + relpos11 + slp50 + solar + tanc75, data = soildata, 
##     method = &quot;class&quot;)
## 
## Variables actually used in tree construction:
## [1] dem10m     eastness   landsatb7  minc100    northeastn planc100   protection
## [8] tanc75    
## 
## Root node error: 109/250 = 0.436
## 
## n= 250 
## 
##         CP nsplit rel error  xerror     xstd
## 1 0.256881      0   1.00000 1.00000 0.071933
## 2 0.050459      1   0.74312 0.91743 0.071064
## 3 0.027523      5   0.54128 0.98165 0.071773
## 4 0.010000      8   0.45872 0.90826 0.070943</code></pre>
<p>The <code>printcp()</code> funtion generates a cost complexity parameter table that provides the complexity parameter value (CP), relative model error (1 - relative error = ~variance explained), error estimated from a 10-fold cross validation (xerror), and the standard error of the xerror (xstd). The CP values control the size of the tree; the greater the CP value, the fewer the number of splits in the tree. To determine the optimal CP value, rpart automatically performs a 10-fold cross validation. The optimal size of the tree is generally the row in the CP table that minimizes all error with the fewest branches. Another way to determine the optimal tree size is to use the <code>plotcp()</code> function. This will plot the xerror versus cp value and tree size.</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="tree-based-models.html#cb192-1"></a><span class="kw">plotcp</span>(spodintmodel)</span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="tree-based-models.html#cb193-1"></a><span class="kw">plotcp</span>(spodintmodel2)</span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<p>The optimal CP value is 0.029321 for spodintmodel and 0.050459 for spodintmodel2. Since both spodic intensity models overfit that data, they will need to be pruned using the <code>prune()</code> function.</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="tree-based-models.html#cb194-1"></a>pruned &lt;-<span class="st"> </span><span class="kw">prune</span>(spodintmodel, <span class="dt">cp=</span><span class="fl">0.029321</span>)</span>
<span id="cb194-2"><a href="tree-based-models.html#cb194-2"></a><span class="kw">printcp</span>(pruned)</span></code></pre></div>
<pre><code>## 
## Classification tree:
## rpart(formula = spodint ~ rainfall + geology + aachn + dem10m + 
##     downslpgra + eastness + greenrefl + landsatb1 + landsatb2 + 
##     landsatb3 + landsatb7 + maxc100 + maxent + minc100 + mirref + 
##     ndvi + northeastn + northness + northwestn + planc100 + proc100 + 
##     protection + relpos11 + slp50 + solar + tanc75, data = soildata, 
##     method = &quot;class&quot;)
## 
## Variables actually used in tree construction:
## [1] northwestn protection
## 
## Root node error: 162/250 = 0.648
## 
## n= 250 
## 
##         CP nsplit rel error  xerror     xstd
## 1 0.179012      0   1.00000 1.00000 0.046614
## 2 0.030864      1   0.82099 0.90123 0.048107
## 3 0.029321      2   0.79012 0.91358 0.047967</code></pre>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="tree-based-models.html#cb196-1"></a><span class="kw">rpart.plot</span>(pruned, <span class="dt">extra=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-13-1.png" width="288" /></p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="tree-based-models.html#cb197-1"></a>pruned2 &lt;-<span class="st"> </span><span class="kw">prune</span>(spodintmodel2, <span class="dt">cp=</span><span class="fl">0.050459</span>)</span>
<span id="cb197-2"><a href="tree-based-models.html#cb197-2"></a><span class="kw">printcp</span>(pruned2)</span></code></pre></div>
<pre><code>## 
## Classification tree:
## rpart(formula = newcolumn ~ rainfall + geology + aachn + dem10m + 
##     downslpgra + eastness + greenrefl + landsatb1 + landsatb2 + 
##     landsatb3 + landsatb7 + maxc100 + maxent + minc100 + mirref + 
##     ndvi + northeastn + northness + northwestn + planc100 + proc100 + 
##     protection + relpos11 + slp50 + solar + tanc75, data = soildata, 
##     method = &quot;class&quot;)
## 
## Variables actually used in tree construction:
## [1] eastness
## 
## Root node error: 109/250 = 0.436
## 
## n= 250 
## 
##         CP nsplit rel error  xerror     xstd
## 1 0.256881      0   1.00000 1.00000 0.071933
## 2 0.050459      1   0.74312 0.91743 0.071064</code></pre>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="tree-based-models.html#cb199-1"></a><span class="kw">rpart.plot</span>(pruned2, <span class="dt">extra=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-13-2.png" width="288" /></p>
<p>The misclassification rate (in cross-validation) for the spodintmodel was 57% (root node error * xerror * 100) which dropped to 38% in the spodintmodel2. Why did the performance of these models differ significantly?</p>
<p>Let’s compute an internal validation using a confusion matrix to further examine differences in these models. In order to do this, we will need to split our data into a training and test set.</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="tree-based-models.html#cb200-1"></a><span class="co">## splits 70% of the data selected randomly into training set and the remaining 30% sample into test set</span></span>
<span id="cb200-2"><a href="tree-based-models.html#cb200-2"></a>datasplit &lt;-<span class="st"> </span><span class="kw">sort</span>(<span class="kw">sample</span>(<span class="kw">nrow</span>(soildata), <span class="kw">nrow</span>(soildata)<span class="op">*</span>.<span class="dv">7</span>)) </span>
<span id="cb200-3"><a href="tree-based-models.html#cb200-3"></a>train &lt;-<span class="st"> </span>soildata[datasplit,]</span>
<span id="cb200-4"><a href="tree-based-models.html#cb200-4"></a>test &lt;-<span class="st"> </span>soildata[<span class="op">-</span>datasplit,]</span>
<span id="cb200-5"><a href="tree-based-models.html#cb200-5"></a></span>
<span id="cb200-6"><a href="tree-based-models.html#cb200-6"></a>spodintmodel &lt;-<span class="st"> </span><span class="kw">rpart</span>(spodint <span class="op">~</span><span class="st"> </span>rainfall <span class="op">+</span><span class="st"> </span>geology <span class="op">+</span><span class="st"> </span>aachn <span class="op">+</span><span class="st"> </span>dem10m <span class="op">+</span><span class="st"> </span>downslpgra <span class="op">+</span><span class="st"> </span>eastness <span class="op">+</span><span class="st"> </span>greenrefl <span class="op">+</span><span class="st"> </span>landsatb1 <span class="op">+</span><span class="st"> </span>landsatb2 <span class="op">+</span><span class="st"> </span>landsatb3 <span class="op">+</span>landsatb7 <span class="op">+</span><span class="st"> </span>maxc100 <span class="op">+</span><span class="st"> </span>maxent <span class="op">+</span><span class="st"> </span>minc100 <span class="op">+</span><span class="st"> </span>mirref <span class="op">+</span><span class="st"> </span>ndvi<span class="op">+</span><span class="st"> </span>northeastn <span class="op">+</span><span class="st"> </span>northness <span class="op">+</span><span class="st"> </span>northwestn <span class="op">+</span><span class="st"> </span>planc100 <span class="op">+</span><span class="st"> </span>proc100 <span class="op">+</span><span class="st"> </span>protection <span class="op">+</span><span class="st"> </span>relpos11 <span class="op">+</span><span class="st"> </span>slp50 <span class="op">+</span><span class="st"> </span>solar <span class="op">+</span><span class="st"> </span>tanc75, <span class="dt">data =</span> train, <span class="dt">method =</span> <span class="st">&quot;class&quot;</span>)</span>
<span id="cb200-7"><a href="tree-based-models.html#cb200-7"></a><span class="kw">printcp</span>(spodintmodel)</span></code></pre></div>
<pre><code>## 
## Classification tree:
## rpart(formula = spodint ~ rainfall + geology + aachn + dem10m + 
##     downslpgra + eastness + greenrefl + landsatb1 + landsatb2 + 
##     landsatb3 + landsatb7 + maxc100 + maxent + minc100 + mirref + 
##     ndvi + northeastn + northness + northwestn + planc100 + proc100 + 
##     protection + relpos11 + slp50 + solar + tanc75, data = train, 
##     method = &quot;class&quot;)
## 
## Variables actually used in tree construction:
## [1] dem10m     downslpgra maxc100    maxent     northwestn planc100   proc100   
## [8] solar     
## 
## Root node error: 118/175 = 0.67429
## 
## n= 175 
## 
##         CP nsplit rel error  xerror     xstd
## 1 0.186441      0   1.00000 1.00000 0.052538
## 2 0.059322      1   0.81356 0.87288 0.055168
## 3 0.050847      2   0.75424 0.96610 0.053422
## 4 0.038136      3   0.70339 0.91525 0.054494
## 5 0.025424      5   0.62712 0.85593 0.055383
## 6 0.021186      6   0.60169 0.84746 0.055479
## 7 0.010000      9   0.53390 0.84746 0.055479</code></pre>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="tree-based-models.html#cb202-1"></a>pruned &lt;-<span class="st"> </span><span class="kw">prune</span>(spodintmodel, <span class="dt">cp=</span><span class="fl">0.070175</span>)</span>
<span id="cb202-2"><a href="tree-based-models.html#cb202-2"></a>pred &lt;-<span class="st"> </span><span class="kw">predict</span>(pruned, <span class="dt">newdata=</span>test, <span class="dt">type=</span><span class="st">&quot;class&quot;</span>) <span class="co">#predicting class test data using the pruned model</span></span>
<span id="cb202-3"><a href="tree-based-models.html#cb202-3"></a><span class="kw">confusionMatrix</span>(pred, test<span class="op">$</span>spodint) <span class="co">#computes confusion matrix and summary statistics</span></span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction  0 0.5  1 1.5  2
##        0   22   2 10   1  7
##        0.5  0   0  0   0  0
##        1    0   0  0   0  0
##        1.5  0   0  0   0  0
##        2    9   5  6   0 13
## 
## Overall Statistics
##                                           
##                Accuracy : 0.4667          
##                  95% CI : (0.3505, 0.5855)
##     No Information Rate : 0.4133          
##     P-Value [Acc &gt; NIR] : 0.2053          
##                                           
##                   Kappa : 0.181           
##                                           
##  Mcnemar&#39;s Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: 0 Class: 0.5 Class: 1 Class: 1.5 Class: 2
## Sensitivity            0.7097    0.00000   0.0000    0.00000   0.6500
## Specificity            0.5455    1.00000   1.0000    1.00000   0.6364
## Pos Pred Value         0.5238        NaN      NaN        NaN   0.3939
## Neg Pred Value         0.7273    0.90667   0.7867    0.98667   0.8333
## Prevalence             0.4133    0.09333   0.2133    0.01333   0.2667
## Detection Rate         0.2933    0.00000   0.0000    0.00000   0.1733
## Detection Prevalence   0.5600    0.00000   0.0000    0.00000   0.4400
## Balanced Accuracy      0.6276    0.50000   0.5000    0.50000   0.6432</code></pre>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="tree-based-models.html#cb204-1"></a><span class="co">#sensitivity=producer&#39;s accuracy and specificity=user&#39;s accuracy</span></span>
<span id="cb204-2"><a href="tree-based-models.html#cb204-2"></a></span>
<span id="cb204-3"><a href="tree-based-models.html#cb204-3"></a>spodintmodel2 &lt;-<span class="st"> </span><span class="kw">rpart</span>(newcolumn <span class="op">~</span><span class="st"> </span>rainfall <span class="op">+</span><span class="st"> </span>geology <span class="op">+</span><span class="st"> </span>aachn <span class="op">+</span><span class="st"> </span>dem10m <span class="op">+</span><span class="st"> </span>downslpgra <span class="op">+</span><span class="st"> </span>eastness <span class="op">+</span><span class="st"> </span>greenrefl <span class="op">+</span><span class="st"> </span>landsatb1 <span class="op">+</span><span class="st"> </span>landsatb2 <span class="op">+</span><span class="st"> </span>landsatb3 <span class="op">+</span>landsatb7 <span class="op">+</span><span class="st"> </span>maxc100 <span class="op">+</span><span class="st"> </span>maxent <span class="op">+</span><span class="st"> </span>minc100 <span class="op">+</span><span class="st"> </span>mirref <span class="op">+</span><span class="st"> </span>ndvi<span class="op">+</span><span class="st"> </span>northeastn <span class="op">+</span><span class="st"> </span>northness <span class="op">+</span><span class="st"> </span>northwestn <span class="op">+</span><span class="st"> </span>planc100 <span class="op">+</span><span class="st"> </span>proc100 <span class="op">+</span><span class="st"> </span>protection <span class="op">+</span><span class="st"> </span>relpos11 <span class="op">+</span><span class="st"> </span>slp50 <span class="op">+</span><span class="st"> </span>solar <span class="op">+</span><span class="st"> </span>tanc75, <span class="dt">data =</span> train, <span class="dt">method =</span> <span class="st">&quot;class&quot;</span>)</span>
<span id="cb204-4"><a href="tree-based-models.html#cb204-4"></a><span class="kw">printcp</span>(spodintmodel2)</span></code></pre></div>
<pre><code>## 
## Classification tree:
## rpart(formula = newcolumn ~ rainfall + geology + aachn + dem10m + 
##     downslpgra + eastness + greenrefl + landsatb1 + landsatb2 + 
##     landsatb3 + landsatb7 + maxc100 + maxent + minc100 + mirref + 
##     ndvi + northeastn + northness + northwestn + planc100 + proc100 + 
##     protection + relpos11 + slp50 + solar + tanc75, data = train, 
##     method = &quot;class&quot;)
## 
## Variables actually used in tree construction:
## [1] downslpgra eastness   landsatb2  maxent     northeastn rainfall   slp50     
## 
## Root node error: 71/175 = 0.40571
## 
## n= 175 
## 
##         CP nsplit rel error  xerror     xstd
## 1 0.225352      0   1.00000 1.00000 0.091489
## 2 0.070423      1   0.77465 0.91549 0.090028
## 3 0.056338      2   0.70423 1.02817 0.091872
## 4 0.042254      3   0.64789 1.02817 0.091872
## 5 0.028169      4   0.60563 1.02817 0.091872
## 6 0.014085      6   0.54930 1.08451 0.092487
## 7 0.010000      7   0.53521 1.08451 0.092487</code></pre>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="tree-based-models.html#cb206-1"></a>pruned2 &lt;-<span class="st"> </span><span class="kw">prune</span>(spodintmodel2, <span class="dt">cp=</span><span class="fl">0.050459</span>)</span>
<span id="cb206-2"><a href="tree-based-models.html#cb206-2"></a>pred2 &lt;-<span class="st"> </span><span class="kw">predict</span>(pruned2, <span class="dt">newdata=</span>test, <span class="dt">type=</span><span class="st">&quot;class&quot;</span>) <span class="co">#predicting class of test data using the pruned model</span></span>
<span id="cb206-3"><a href="tree-based-models.html#cb206-3"></a><span class="kw">confusionMatrix</span>(pred2, test<span class="op">$</span>newcolumn) <span class="co">#computes confusion matrix and summary statistics</span></span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##            Reference
## Prediction  nonspodic spodic
##   nonspodic        22     16
##   spodic           16     21
##                                           
##                Accuracy : 0.5733          
##                  95% CI : (0.4538, 0.6869)
##     No Information Rate : 0.5067          
##     P-Value [Acc &gt; NIR] : 0.1493          
##                                           
##                   Kappa : 0.1465          
##                                           
##  Mcnemar&#39;s Test P-Value : 1.0000          
##                                           
##             Sensitivity : 0.5789          
##             Specificity : 0.5676          
##          Pos Pred Value : 0.5789          
##          Neg Pred Value : 0.5676          
##              Prevalence : 0.5067          
##          Detection Rate : 0.2933          
##    Detection Prevalence : 0.5067          
##       Balanced Accuracy : 0.5733          
##                                           
##        &#39;Positive&#39; Class : nonspodic       
## </code></pre>
<p>The accuracy of the spodintmodel using split sample internal validation was 39% (61% misclassification error). The model incorrectly classified all spodic intensity ratings of 0.5 and 1.5. The accuracy of the spodintmodel2 was 63% (37% misclassification error). The model was able to predict spodic better than nonspodic. Notice that both of the misclassification errors increased slightly using the split sample validation versus the deafult internal 10-fold cross-validation used in by the rpart package. It is not uncommon to see slight differences in overall model performance between validations. In this case, it confirms that the first model is relatively 40% accurate and the second model is relatively 63% accurate.</p>
<p>As a side note: The default 10-fold internal cross-validation in rpart divides the data into 10 subsets, using 9 sets as ‘learning samples’ to create trees, and 1 set as ‘test samples’ to calculate error rates. This process is repeated for all possible combinations of learning and test samples (a total of 10 times), and error rates are averaged to estimate the error rate for the full data set.</p>
<div id="exercise-2-rpart" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Exercise 2: rpart</h3>
<p>The examples above dealt with classification trees which resulted in categorical terminal nodes determined by majority votes. In a regression tree model, terminal nodes reflect the mean of the observations in that node. Using the <strong>soildata</strong> dataset, construct a rpart regression tree model to predict total O horizon thickness. Prune the model if necessary and answer the following questions:</p>
<p>** 1) Was the majority of the variance in total O horizon thickness captured with the rpart model?**</p>
<p>** 2) What were the most important variables in the model?**</p>
<p>** 3) How could the model be improved?**</p>
</div>
</div>
<div id="random-forest" class="section level2">
<h2><span class="header-section-number">5.4</span> Random Forest</h2>
<p>The randomForest algorithm fits hundreds to thousands of CART models to random subsets of input data and combines the trees for prediction. Similarly to rpart, randomForest allows all data types to be used as independent variables, regardless of whether the model is a classification or regression tree. Unlike rpart, the randomForest algorithm does not straight forwardly handle missing values with surrogate splits. There is a function called <code>rfImpute()</code> that uses a proximity matrix from the randomForest to populate missing values with either the weighted average of the non-missing observations (weighted by the proximities) for continuous predictors or the category with the largest average proximity for categorical predictors.</p>
<p>Going back to the <strong>soildata</strong> dataset, let’s generate a random forest regression model for total O horizon thickness and compare it to the one we just generated in rpart. Just like rpart, randomForest has the same basic model function: (y ~ x).</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="tree-based-models.html#cb208-1"></a>rf &lt;-<span class="st"> </span><span class="kw">randomForest</span>(Otot <span class="op">~</span><span class="st"> </span>rainfall <span class="op">+</span><span class="st"> </span>geology <span class="op">+</span><span class="st"> </span>aachn <span class="op">+</span><span class="st"> </span>dem10m <span class="op">+</span><span class="st"> </span>downslpgra <span class="op">+</span><span class="st"> </span>eastness <span class="op">+</span><span class="st"> </span>greenrefl <span class="op">+</span><span class="st"> </span>landsatb1 <span class="op">+</span><span class="st"> </span>landsatb2 <span class="op">+</span><span class="st"> </span>landsatb3 <span class="op">+</span>landsatb7 <span class="op">+</span><span class="st"> </span>maxc100 <span class="op">+</span><span class="st"> </span>maxent <span class="op">+</span><span class="st"> </span>minc100 <span class="op">+</span><span class="st"> </span>mirref <span class="op">+</span><span class="st"> </span>ndvi<span class="op">+</span><span class="st"> </span>northeastn <span class="op">+</span><span class="st"> </span>northness <span class="op">+</span><span class="st"> </span>northwestn <span class="op">+</span><span class="st"> </span>planc100 <span class="op">+</span><span class="st"> </span>proc100 <span class="op">+</span><span class="st"> </span>protection <span class="op">+</span><span class="st"> </span>relpos11 <span class="op">+</span><span class="st"> </span>slp50 <span class="op">+</span><span class="st"> </span>solar <span class="op">+</span><span class="st"> </span>tanc75, <span class="dt">data =</span> soildata, <span class="dt">importance=</span><span class="ot">TRUE</span>, <span class="dt">ntree=</span><span class="dv">1000</span>, <span class="dt">mtry=</span><span class="dv">10</span>) <span class="co">#importance=TRUE will allow the generation of a variable importance plot</span></span>
<span id="cb208-2"><a href="tree-based-models.html#cb208-2"></a></span>
<span id="cb208-3"><a href="tree-based-models.html#cb208-3"></a>rf <span class="co">#statistical summary</span></span></code></pre></div>
<pre><code>## 
## Call:
##  randomForest(formula = Otot ~ rainfall + geology + aachn + dem10m +      downslpgra + eastness + greenrefl + landsatb1 + landsatb2 +      landsatb3 + landsatb7 + maxc100 + maxent + minc100 + mirref +      ndvi + northeastn + northness + northwestn + planc100 + proc100 +      protection + relpos11 + slp50 + solar + tanc75, data = soildata,      importance = TRUE, ntree = 1000, mtry = 10) 
##                Type of random forest: regression
##                      Number of trees: 1000
## No. of variables tried at each split: 10
## 
##           Mean of squared residuals: 28.09843
##                     % Var explained: 21.86</code></pre>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="tree-based-models.html#cb210-1"></a><span class="kw">plot</span>(rf)  <span class="co">#out of bag (OOB) error rate versus number of trees; this will help us tune the ntree parameter</span></span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The rf model, generated using the default number of trees and number of variables tried at each split, explained approximately 23% of the variance and produced a mean square error (sum of squared residuals divided by n) of 28 cm2. If you were to run this same model again, the % variance explained and MSE would change slightly due to the random subsetting and averaging in the randomForest algorithm. <strong>How does this compare with the rpart model?</strong></p>
<p>Recall that the <strong>soildata</strong> dataset had one Histosol observation:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="tree-based-models.html#cb211-1"></a><span class="kw">hist</span>(soildata<span class="op">$</span>Otot)</span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Let’s remove that observation to see how it impacted our model.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="tree-based-models.html#cb212-1"></a>file &lt;-<span class="st"> &#39;https://raw.githubusercontent.com/ncss-tech/stats_for_soil_survey/master/data/logistic/wv_transect_editedforR.csv&#39;</span></span>
<span id="cb212-2"><a href="tree-based-models.html#cb212-2"></a><span class="kw">download.file</span>(file, <span class="dt">destfile =</span> <span class="st">&quot;soildata.csv&quot;</span>)</span>
<span id="cb212-3"><a href="tree-based-models.html#cb212-3"></a>soildata &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;soildata.csv&quot;</span>, <span class="dt">header=</span><span class="ot">TRUE</span>, <span class="dt">sep=</span><span class="st">&quot;,&quot;</span>)</span>
<span id="cb212-4"><a href="tree-based-models.html#cb212-4"></a>soildata2 &lt;-<span class="st"> </span><span class="kw">droplevels</span>(<span class="kw">subset</span>(soildata, order<span class="op">!=</span><span class="st">&quot;histosol&quot;</span>)) <span class="co">#remove Histosol observation</span></span>
<span id="cb212-5"><a href="tree-based-models.html#cb212-5"></a></span>
<span id="cb212-6"><a href="tree-based-models.html#cb212-6"></a>rf2 &lt;-<span class="st"> </span><span class="kw">randomForest</span>(Otot <span class="op">~</span><span class="st"> </span>rainfall <span class="op">+</span><span class="st"> </span>geology <span class="op">+</span><span class="st"> </span>aachn <span class="op">+</span><span class="st"> </span>dem10m <span class="op">+</span><span class="st"> </span>downslpgra <span class="op">+</span><span class="st"> </span>eastness <span class="op">+</span><span class="st"> </span>greenrefl <span class="op">+</span><span class="st"> </span>landsatb1 <span class="op">+</span><span class="st"> </span>landsatb2 <span class="op">+</span><span class="st"> </span>landsatb3 <span class="op">+</span>landsatb7 <span class="op">+</span><span class="st"> </span>maxc100 <span class="op">+</span><span class="st"> </span>maxent <span class="op">+</span><span class="st"> </span>minc100 <span class="op">+</span><span class="st"> </span>mirref <span class="op">+</span><span class="st"> </span>ndvi<span class="op">+</span><span class="st"> </span>northeastn <span class="op">+</span><span class="st"> </span>northness <span class="op">+</span><span class="st"> </span>northwestn <span class="op">+</span><span class="st"> </span>planc100 <span class="op">+</span><span class="st"> </span>proc100 <span class="op">+</span><span class="st"> </span>protection <span class="op">+</span><span class="st"> </span>relpos11 <span class="op">+</span><span class="st"> </span>slp50 <span class="op">+</span><span class="st"> </span>solar <span class="op">+</span><span class="st"> </span>tanc75, <span class="dt">data =</span> soildata2, <span class="dt">importance=</span><span class="ot">TRUE</span>, <span class="dt">ntree=</span><span class="dv">1000</span>, <span class="dt">mtry=</span><span class="dv">9</span>) </span>
<span id="cb212-7"><a href="tree-based-models.html#cb212-7"></a><span class="co">#importance=TRUE will allow the generation of a variable importance plot</span></span>
<span id="cb212-8"><a href="tree-based-models.html#cb212-8"></a></span>
<span id="cb212-9"><a href="tree-based-models.html#cb212-9"></a>rf2 <span class="co"># statistical summary</span></span></code></pre></div>
<pre><code>## 
## Call:
##  randomForest(formula = Otot ~ rainfall + geology + aachn + dem10m +      downslpgra + eastness + greenrefl + landsatb1 + landsatb2 +      landsatb3 + landsatb7 + maxc100 + maxent + minc100 + mirref +      ndvi + northeastn + northness + northwestn + planc100 + proc100 +      protection + relpos11 + slp50 + solar + tanc75, data = soildata2,      importance = TRUE, ntree = 1000, mtry = 9) 
##                Type of random forest: regression
##                      Number of trees: 1000
## No. of variables tried at each split: 9
## 
##           Mean of squared residuals: 24.24666
##                     % Var explained: 22.73</code></pre>
<p><strong>Did removing the outlier Histosol observation improve the model?</strong></p>
<p>The defaults for the number of trees (<code>ntree</code>) and number of variables tried at each split (<code>mtry</code>) may need to be adjusted in the <code>randomForest</code> command to explain more variance in the data and to reduce model over-fitting. For most datasets, manually tweaking these parameters and examining the statistical summary is often sufficient. The <code>tuneRF()</code> function can be used to determine the optimal <code>mtry</code> value, but some users have claimed that this algorithm leads to bias. Feel free to manually tweak the <code>ntree</code> and <code>mtry</code> settings to see how they effect the overall model performance.</p>
<p>Another way to assess the rf model is to look at the variable importance plot.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="tree-based-models.html#cb214-1"></a><span class="kw">varImpPlot</span>(rf2)</span></code></pre></div>
<p><img src="006-treemodels_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="tree-based-models.html#cb215-1"></a>imp &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">sort</span>(<span class="kw">importance</span>(rf2)[,<span class="dv">1</span>],<span class="dt">decreasing =</span> <span class="ot">TRUE</span>),<span class="dt">optional =</span> T)</span>
<span id="cb215-2"><a href="tree-based-models.html#cb215-2"></a><span class="kw">names</span>(imp) &lt;-<span class="st"> &quot;% Inc MSE&quot;</span></span>
<span id="cb215-3"><a href="tree-based-models.html#cb215-3"></a>imp <span class="co"># sorted tabular summary</span></span></code></pre></div>
<pre><code>##             % Inc MSE
## landsatb7  22.2881522
## maxent     18.0479569
## protection 10.7843422
## northwestn  8.2679676
## solar       7.6946079
## rainfall    7.2362535
## downslpgra  6.0682438
## slp50       5.5789709
## minc100     5.2974000
## aachn       5.0169593
## dem10m      4.6986309
## eastness    4.5805129
## maxc100     4.1549669
## relpos11    4.1451131
## northeastn  4.1421563
## northness   4.1022384
## planc100    4.0799308
## proc100     3.8260886
## greenrefl   3.3736472
## geology     2.7520274
## landsatb2   2.6020824
## landsatb3   1.6680639
## landsatb1   1.6473007
## tanc75      0.9004840
## ndvi        0.8694725
## mirref      0.4696301</code></pre>
<p>For each tree, each predictor in the OOB sample is randomly permuted and passed through the tree to obtain an error rate (mean square error (MSE) for regression and Gini index for classification). The error rate from the unpermuted OOB is then subtracted from the error rate of the permuted OOB data, and averaged across all trees. When this value is large, it implies that a variable is highly correlated to the dependent variable and is needed in the model.</p>
<p>In a regression tree analysis, randomForest uses %IncMSE and IncNodePurity to rank variable importance. %IncMSE is simply the average increase in squared residuals of the test set when variables are randomly permuted (little importance = little change in model when variable is removed or added) and IncNodePurity is the increase in homogeneity in the data partitions. In a classification tree analysis, randomForest uses MeanDecreaseAccuracy and MeanDecreaseGini. For MeanDecreaseAccuracy, the more the accuracy of the model decreases due to the addition of a single variable, the more important the variable is deemed. MeanDecreaseGini is a measure of how each variable contributes to the homogeneity of the nodes and leaves.</p>
<p>In the rf2 model, it is apparent that landsatb7 is the most important variable used in the model, followed by maxent, protection index, northwestness, solar, and rainfall.</p>
<div id="exercise-3-randomforest" class="section level3">
<h3><span class="header-section-number">5.4.1</span> Exercise 3: randomForest</h3>
<p>Using the <strong>soildata</strong> dataset, construct a randomForest model to predict the probability of a folistic epipedon. Be sure to tweak the ntree and mtry parameters to capture the most variability. Use the following code to combine ochric and umbric into a new category called nonfolistic.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="tree-based-models.html#cb217-1"></a>soildata<span class="op">$</span>epipedon2 &lt;-<span class="st"> </span>soildata<span class="op">$</span>epipedon</span>
<span id="cb217-2"><a href="tree-based-models.html#cb217-2"></a><span class="kw">levels</span>(soildata<span class="op">$</span>epipedon2)[<span class="kw">levels</span>(soildata<span class="op">$</span>epipedon2)<span class="op">==</span><span class="st">&quot;ochric&quot;</span>] &lt;-<span class="st"> &quot;nonfolistic&quot;</span></span>
<span id="cb217-3"><a href="tree-based-models.html#cb217-3"></a><span class="kw">levels</span>(soildata<span class="op">$</span>epipedon2)[<span class="kw">levels</span>(soildata<span class="op">$</span>epipedon2)<span class="op">==</span><span class="st">&quot;umbric&quot;</span>] &lt;-<span class="st"> &quot;nonfolistic&quot;</span></span></code></pre></div>
<p>** 1) What is the out-of-bag error rate?**</p>
<p>** 2) Compare this model with the total O horizon thickness regression model. Which would be better for spatial interpolation?**</p>
<p>** 3) How could you improve this model?**</p>
</div>
</div>
<div id="prediction-using-tree-based-models" class="section level2">
<h2><span class="header-section-number">5.5</span> Prediction using Tree-based Models</h2>
<p>As with any modeling technique, tree-based models can be used for prediction and can be spatially interpolated using environmental covariates. In order to interpolate a model, R requires that all raster images have a common datum, common cell resolution, are coregistered, and are preferably .img files. The function <code>stack()</code> combines all of the rasters into a “raster stack.” The <code>predict()</code> function is then used in the form of: <code>predict(rasterstack, fittedmodel, type="")</code>. Follow along through the example below to interpolate the rpart total O horizon thickness model:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="tree-based-models.html#cb218-1"></a><span class="kw">library</span>(raster)</span>
<span id="cb218-2"><a href="tree-based-models.html#cb218-2"></a>rasters &lt;-<span class="st"> </span><span class="kw">stack</span>(<span class="kw">list.files</span>(<span class="kw">getwd</span>(),<span class="dt">pattern=</span><span class="st">&quot;img$&quot;</span>,<span class="dt">full.names=</span><span class="ot">FALSE</span>)) <span class="co">#combines rasters with a .img file extension stored in the working directory</span></span>
<span id="cb218-3"><a href="tree-based-models.html#cb218-3"></a></span>
<span id="cb218-4"><a href="tree-based-models.html#cb218-4"></a>rasters </span>
<span id="cb218-5"><a href="tree-based-models.html#cb218-5"></a></span>
<span id="cb218-6"><a href="tree-based-models.html#cb218-6"></a>model &lt;-<span class="st"> </span><span class="kw">randomForest</span>(Otot<span class="op">~</span>landsatb7<span class="op">+</span>maxent<span class="op">+</span>protection<span class="op">+</span>northwestn<span class="op">+</span>solar, <span class="dt">data=</span>soildata2)</span>
<span id="cb218-7"><a href="tree-based-models.html#cb218-7"></a></span>
<span id="cb218-8"><a href="tree-based-models.html#cb218-8"></a><span class="kw">predict</span>(rasters,model,<span class="dt">progress=</span><span class="st">&quot;window&quot;</span>,<span class="dt">overwrite=</span><span class="ot">TRUE</span>,<span class="dt">filename=</span><span class="st">&quot;rfpredict.img&quot;</span>) </span>
<span id="cb218-9"><a href="tree-based-models.html#cb218-9"></a><span class="co">#type not specified=vector of predicted values, &quot;response&quot; for predicted class, &quot;prob&quot; for probabilities, or &quot;vote&quot; for matrix of vote counts (one column for each class and one row for each new input); either in raw counts or in fractions (if norm.votes=TRUE)</span></span>
<span id="cb218-10"><a href="tree-based-models.html#cb218-10"></a></span>
<span id="cb218-11"><a href="tree-based-models.html#cb218-11"></a><span class="co">#options for predicting rpart model: type= &quot;vector&quot; for mean response at the node, &quot;prob&quot; for matrix of class probabilities, or &quot;class&quot; for a factor of classifications based on the responses</span></span></code></pre></div>
<p>The output raster “rfpredict.img” can be added and viewed in ArcMap.</p>
<div class="figure">
<img src="figure/ch8_predicted.jpg" alt="" />
<p class="caption">R GUI image</p>
</div>
<p>You can also view the interpolated model in R:</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="tree-based-models.html#cb219-1"></a>rfpredict &lt;-<span class="st"> </span><span class="kw">raster</span>(<span class="st">&quot;rfpredict.img&quot;</span>)</span>
<span id="cb219-2"><a href="tree-based-models.html#cb219-2"></a><span class="kw">plot</span>(rfpredict, <span class="dt">xlab=</span><span class="st">&quot;Easting (m)&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Northing (m)&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Total O Horizon Thickness (cm)&quot;</span>)</span></code></pre></div>
</div>
<div id="summary" class="section level2">
<h2><span class="header-section-number">5.6</span> Summary</h2>
<p>Tree-based models are intuitive, quick to run, nonparametric, and are often ideal for exploratory data analysis and prediction. Both rpart and randomForest produce graphical and tabular outputs to aid interpretation. Both packages also perform internal validataion (rpart=10-fold cross validation; randomForest=OOB error estimates) to assess model performance. Tree-based models do require pruning and/or tweaking of model parameters to reduce over-fitting and are unstable in that removing observations (especially outliers) or independent predictors can greatly alter the tree structure. In general, tree-based models are robust against multicollinearity and low n, high p datasets (low sample size and many predictors).</p>
</div>
<div id="additional-reading-2" class="section level2">
<h2><span class="header-section-number">5.7</span> Additional Reading</h2>
<p>Gareth, J., D. Witten, T. Hastie, and R. Tibshirani, 2014. An Introduction to Statistical Learning: with Applications in R. Springer, New York. <a href="http://www-bcf.usc.edu/~gareth/ISL/">http://www-bcf.usc.edu/~gareth/ISL/</a></p>
<p>Rad, M.R.P., N. Toomanian, F. Khormali, C.W. Brungard, C.B. Komaki, and P. Bogaert. 2014. Updating soil survey maps using random forest and conditioned Latin hypercube sampling in the loess derived soils of northern Iran. Geoderma. 232-234: 97-106.</p>
</div>
<div id="references-tree-based-models" class="section level2">
<h2><span class="header-section-number">5.8</span> References (Tree-based Models)</h2>

</div>
</div>



## Attaching package: &#39;igraph&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     decompose, spectrum</code></pre>
<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     union</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## Warning: package &#39;wesanderson&#39; was built under R version 4.0.5</code></pre>
<pre><code>## This is aqp 1.30</code></pre>
<pre><code>## 
## Attaching package: &#39;aqp&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:plyr&#39;:
## 
##     mutate, summarize</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     filter</code></pre>
<pre><code>## Warning: package &#39;kableExtra&#39; was built under R version 4.0.4</code></pre>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="glm.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="acc-unc-categorical-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["s4ssbook.pdf", "s4ssbook.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
