---
title: "7_Generalized_linear_models"
author: "Stephen Roecker"
date: "January 6, 2016"
output: 
 html_document: 
    toc: yes
---

# Introduction

Generalized linear models (GLM) as the name implies are a generalization of the linear modeling framework to allow for the modeling of response variables (e.g. soil attributes) with non-normal distributions and heterogeneous variances. Whereas linear models are designed for predicting continuous soil properties such as clay content or temperature, GLM for example can be used to predict the presence/absence of argillic horizons (i.e. logistic regression) or soil nutrients. This greatly expands the applicable of the linear modeling framework, while still allowing for a similar fitting procedure and interpretation of the resulting models.  

In the past in order to handle non-linearity and heterogeneous variances, transformations have been made to the response variable, such as the log(x). However such transformations complicate the models interpretation because the results refer to the transformed scale (e.g. log(x)). Also previous transformations were not guaranteed to achieve both normality and constant variance. GLM likewise transform the response, but provide separate functions to transform the mean response and variance, know as the link and variance functions respectively. In addition to transforming the response, GLM also report the results in the original scale of the response variable.

In order to allow for 

```{r}
library(soilDB)
library(raster)
library(rgdal)
library(lattice)
library(reshape2)
library(plyr)
library(dplyr)
library(caret)

# Read in data
pedons <- fetchNASIS()


# Exploratory analysis
summary(pedons$argillic.horizon)
summary(grepl("arg", pedons$tax_subgroup))
barplot(table(pedons$argillic.horizon))

d <- diagnostic_hz(pedons)
idx <- unique(d[d$diag_kind == "argillic horizon" & d$featdept < 50, "peiid"])
pedons$argillic.horizon <- site(pedons)$peiid %in% idx
summary(pedons$argillic.horizon)

s <- site(pedons)
s$surface_gravel <- s$surface_gravel-s$surface_fgravel
s$surface_total <- apply(s[, grepl("surface", names(s))], 1, sum)
s$pavement <- ifelse(s$slope_field < 15, s$surface_total, NA)
s$bedrckdepth <- ifelse(s$slope_field < 15, s$bedrckdepth, NA)
s_m <- melt(s[c("argillic.horizon", "slope_field", "elev_field", "bedrckdepth", "pavement")], id = "argillic.horizon")
bwplot(argillic.horizon ~ value | variable, data = s_m, scales = list(x = "free"))


# Plot coordinates
idx <- complete.cases(site(pedons)[c("x", "y")])
pedons2 <- pedons[idx]
coordinates(pedons2) <- ~ x + y
proj4string(pedons2) <- CRS("+init=epsg:4326")

ssa <- readOGR(dsn = "M:/geodata/soils", layer = "soilsa_a_nrcs")
ca794 <- subset(ssa, areasymbol == "CA794")
plot(ca794)
pedons_sp <- as(pedons2, "SpatialPointsDataFrame")
plot(pedons_sp, add = TRUE)
pedons_sp <- spTransform(pedons_sp, CRS("+init=epsg:5070"))
writeOGR(pedons_sp, dsn = "M:/geodata/project_data/8VIC", "pedon_locations", driver = "ESRI Shapefile")


# Argillic by soil scientist, bias?
desc_test <- function(old) {
  if (is.na(old)) {new <- "other"}
  if (grepl("Stephen", old)) {new <- "Stephen"} 
  if (grepl("Paul", old)) {new <- "Paul"} 
  if (grepl("Peter", old)) {new <- "Peter"} 
  if (!any(new %in% c("Stephen", "Paul", "Peter"))) {new <- "other"}
 return(new)
}
  or (i in seq_along(x)if (grepl("Stephen", s$describer)) "Stephen"
                if (grepl("Paul", s$describer)) "Paul"
                if (grepl("Peter", s$describer)) "Peter"

test <- with(s, table(describer, argillic.horizon))
test_df1 <- as.data.frame(test[, 1:2])
test_df1_sort <- test_df1[order(test_df1["TRUE"], decreasing = TRUE), ]
head(test_df1_sort)

test2 <- round(prop.table(test, 1) * 100)
test_df2 <- as.data.frame(test2[, 1:2])
test_df2_sort<- test_df2[order(test_df1["TRUE"], decreasing = TRUE), ]
head(test_df2_sort)

# Geodata extract
folder1 <- "M:/geodata/project_data/8VIC/"
folder2 <- "M:/geodata/imagery/gamma/"
files1 <- list(
  terrain = c(
    elev    = "ned30m_8VIC.tif",
    slope   = "ned30m_8VIC_slope5.tif",
    aspect  = "ned30m_8VIC_aspect5.tif",
    twi     = "ned30m_8VIC_wetness.tif",
    z2str   = "ned30m_8VIC_z2stream.tif",
    mrrtf   = "ned30m_8VIC_mrrtf.tif",
    mrvbf   = "ned30m_8VIC_mrvbf.tif",
    #  solar   = "ned30m_vic8_solar.tif",
    solarcv = "ned30m_vic8_solarcv.tif"
    ),
  climate = c(
    precip  = "prism30m_vic8_ppt_1981_2010_annual_mm.tif",
    precipsum = "prism30m_vic8_ppt_1981_2010_summer_mm.tif",
    temp    = "prism30m_vic8_tavg_1981_2010_annual_C.tif"
    ),
  imagery = c(
    ls = "landsat30m_vic8_b123457.tif",
    tc      = "landsat30m_vic8_tc123.tif"
    )
)
files2 <- list(
  gamma = c(
    k  = "namrad_k_aea.tif",
    th = "namrad_th_aea.tif",
    u  = "namrad_u_aea.tif"
    )
)
geodata <- c(lapply(files1, function(x) paste0(folder1, x)), lapply(files2, function(x) paste0(folder2, x))) 
names(geodata$terrain) <- names(files1$terrain)
names(geodata$climate) <- names(files1$climate)
names(geodata$imagery) <- names(files1$imagery)
names(geodata$gamma) <- names(files2$gamma)

geodata_df <- data.frame(
  as.data.frame(pedons_sp)[c("argillic.horizon", "x_std", "y_std", "describer")],
  extract(stack(geodata$terrain[1:7]), pedons_sp),
  extract(raster(geodata$terrain[8]), pedons_sp),
  extract(stack(geodata$imagery), pedons_sp),
  extract(stack(geodata$gamma), pedons_sp),
  extract(stack(geodata$climate), pedons_sp)
  )
names(geodata_df)[c(12, 21)] <- c("solarcv", "ls_7")

geodata_idx <- list()
geodata_idx$terrain <- names(files1$terrain)
geodata_idx$climate <- names(files1$climate)
geodata_idx$imagery <- names(geodata_df)[!names(geodata_df) %in% names(files1$terrain) &
                                        !names(geodata_df) %in% names(files1$climate) &
                                        !names(geodata_df) %in% names(files2$gamma) &
                                        !names(geodata_df) %in% c("argillic.horizon", "x_std", "y_std")]
geodata_idx$gamma <- names(files2)

data <- subset(geodata_df, select = - c(x_std, y_std, describer))
save(data, file = "C:/workspace/stats_for_soil_survey/trunk/data/ch7_data.Rdata")

data$argillic.horizon <- data$mrvbf > 0.15 & data$argillic.horizon == TRUE
data_m <- melt(data, id = "argillic.horizon")
bwplot(argillic.horizon ~ value | variable, data = data_m, scales = list(x = "free"), as.table = TRUE)

source("M:/software/R/")

aggregate(data[c("twi", "z2str")], list(data$argillic.horizon), summary)
data$twi_sc <- abs(data$twi - 13.7)
data$z2str_sc <- abs(data$z2str - 13.9)

test <- glm(argillic.horizon ~., data = data, family = binomial())
summary(test)
confusionMatrix(test$fitted.values > 0.5, as.logical(test$y))
```



