---
title: "Final Project"
date: "`r Sys.Date()`"
output: html_vignette
---

The final project is intended to give you an opportunity to practice the skills covered in this course. Your mentor will be available to assist you with your project should you encounter difficulties, and can help you select a worthwhile question to test. You are strongly encouraged to use your own data, but you may select one of the datasets provided during the class. Examples of previously successful projects are listed below. If you formulate a question for your final project the first day of class, you maybe able to practice with your own data each day before and after class, and finish your final project promptly.

Your project should follow the outline listed below, which generally represents the minimum requirement for all NASIS projects and scientific reports. Keep in mind, just because this course was taught online, doesn't mean it was intended to be any easier than say SGI, nor held to a lesser level. Projects that are incomplete will be returned with feedback, and the participants will be given another try.

-   Objective or hypothesis
-   Study area
-   Results
-   Conclusion or Discussion

Be sure to demonstrate several statistical techniques from the part of the course you're enrolled in.

-   **Part 1:** Use techniques from chapter 1 - 4
-   **Part 2:** Use techniques from chapter 2 - 6.

## Objective(s)

Describe the objective of your project or a hypothesis that you wish to test. Also, briefly discuss the methods that will be used. Communication is key. If you can't explain what your doing and why you're doing it, why should anyone care. It is not necessary to construct an elaborate objective or hypothesis. Often small concrete examples are best. For example, comparing two similar soils or ecosites are great projects because they provide some context from which to interpret the results. Ideally most NASIS projects are intended to update SSURGO, therefore a comparison of component vs pedon data would also be productive.

## Study Area

Briefly describe the dataset you selected and the geographic setting. Be sure to include a map.

If you plan to use spatial data, be sure to develop all of the associated data layers. Your data will need to share a common projection, resolution, extent, GDAL format (ideally img or tiff), be modest in extent (\~2,000 x 2,000 cells) and be co-registered. **Ideally, use a dataset that has been prepared previously**.

If you choose to use a project area from one of the classroom examples, spatial data will be available.

If necessary, your instructor may ask for a copy of your data.

## Results

Include the code used to generate your results, and any tables, figures or output that were generated. At each step describe your results. Provide enough information, such that someone else could duplicate your results. The most likely person to benefit from your documentation, will be the 'future' you.

## Conclusion or Discussion

Discuss how your results:

1.  helped in understanding the problem,
2.  will influence current and future investigations and
3.  how do your results compare to previous work, other studies or the conventional wisdom

Focus on interpreting the results of your data and methods. Your summary need not be lengthly, but it should address the main points and your original objective or hypothesis. This is not the place to discuss the pros and cons of R, or critique the course.

## Examples

-   [Example #1](http://ncss-tech.github.io/stats_for_soil_survey/misc/10_final_project/examples/Paolucci_stats101_2_20_2024.html)
-   [Example #2](http://ncss-tech.github.io/stats_for_soil_survey/misc/10_final_project/examples/fy22_speck_fp1.html)
- [Example #3](https://github.com/ncss-tech/stats_for_soil_survey/raw/master/misc/10_final_project/examples/Statistics%20Final%20Project.docx)
-   [Example #4](http://ncss-tech.github.io/stats_for_soil_survey/misc/10_final_project/examples/Ecological_Site_Differentiation.html)
-   [Example #5](http://ncss-tech.github.io/stats_for_soil_survey/misc/10_final_project/examples/fy23_fp3_Speck.html)


## Due Date

Feb 14th, 2025

Email your final project to your mentor for review, and cc Stephen Roecker.

## Formatting

You can compile your final project using either Word or RMarkdown. RMarkdown is quite simple and will allow you to seamlessly combine your discussion, code, tables and figures into a self-contained Word or HTML file. See the following link for details on generating [RMarkdown Documents](https://rmarkdown.rstudio.com/html_document_format.html). A template is also provide below.

Templates:

-   [RMarkdown Output](https://ncss-tech.github.io/stats_for_soil_survey/misc/10_final_project/final-project-example.html) \| [RMarkdown Source](https://raw.githubusercontent.com/ncss-tech/stats_for_soil_survey/master/misc/10_final_project/final-project-example.Rmd)
